### ISSUE TITLE
mips架构长时间运行3-5小时后整机重启

### ISSUE THREAD

**Issue by 13653216371** [EasyTier/EasyTier#112]
openwrt 64M内存设备，正常情况下内存使用情况如下：
![image](https://github.com/EasyTier/EasyTier/assets/110286972/a3ce6437-670d-4447-9c37-5d3f158e3fa3)

**Comment by KKRainbow** [comment]
我在我的 mips 上跑跑看

**Comment by KKRainbow** [comment]
确实有异常的内存上涨。重启可能因为 oom 了，我调查下

**Comment by KKRainbow** [comment]
https://github.com/EasyTier/EasyTier/pull/116
这个合入后应该能修复此问题

**Comment by KKRainbow** [comment]
跑了一天，确认没有内存泄漏。
另外引入此 patch 后性能又提高了很多。很神奇

**Comment by 13653216371** [comment]
目前跑了4h 54m 13s，似乎是可以了。ping值也稳定了，不知道是不是心理作用

**Comment by KKRainbow** [comment]
> 目前跑了4h 54m 13s，似乎是可以了。ping值也稳定了，不知道是不是心理作用

我现在跑 mips 上的性能，比 vnt 还快一点。估计是内存用量少了之后 cache miss 也变少了。

**Comment by 13653216371** [comment]
经过群里R打流测试，已经超越VNT了

**Comment by KKRainbow** [comment]
> 经过群里R打流测试，已经超越VNT了

不错，意外之喜，有测试结果贴图么，可以分享下不

**Comment by 13653216371** [comment]
![LYW$2AK88FV@KW3P6P2TWLK](https://github.com/EasyTier/EasyTier/assets/110286972/333aeae7-fed4-40ee-82e8-a98f61234ed9)
![3@K%@6LZ5F_8Z8TEESELWXS](https://github.com/EasyTier/EasyTier/assets/110286972/27fd269a-664a-474b-9fe5-0bee201176f8)
![7SJI`%6%WH3@I83SM7CB__V](https://github.com/EasyTier/EasyTier/assets/110286972/baf48058-3836-4a77-a431-291cb7d436c9)
![095 EIWZA6W6U0{9XTCLRG](https://github.com/EasyTier/EasyTier/assets/110286972/33a143e4-9e9c-4dde-bb07-6001926d1b2e)

**Comment by KKRainbow** [comment]
效果显著啊 😄
