### ISSUE TITLE
没有root权限报错

### ISSUE THREAD

**Issue by aurorax-neo** [EasyTier/EasyTier#117]
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: TunError(Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }))), location: Location { file: "easytier/src/easytier-core.rs", line: 444, col: 22 }, can_unwind: true, force_no_backtrace: false }

如何解决？

**Comment by KKRainbow** [comment]
tun 设备需要 sudo 权限。
sudo 执行

**Comment by aurorax-neo** [comment]
> tun 设备需要 sudo 权限。
> 
> sudo 执行

好的 谢谢
