### ISSUE TITLE
功能建议/优化

### ISSUE THREAD

**Issue by aurorax-neo** [EasyTier/EasyTier#119]
能否支持被访问节点不建立tun模式，只需要外部能访问到这个不建立tun的节点，这个没有 tun 的节点不需要访问其它节点，有些特殊情况无法获取 su 权限导致无法建立 tun

**Comment by KKRainbow** [comment]
这个功能有，但是还没有 release。

不填 ipv4 就不会用 tun 设备

**Comment by aurorax-neo** [comment]
> 这个功能有，但是还没有 release。
> 
> 
> 
> 不填 ipv4 就不会用 tun 设备

好的 谢谢.

**Comment by aurorax-neo** [comment]
> 这个功能有，但是还没有 release。
> 
> 不填 ipv4 就不会用 tun 设备

不填 ipv4 的节点该如何访问呢？

**Comment by KKRainbow** [comment]
https://github.com/EasyTier/EasyTier/pull/141
实现了一个无 tun 模式。这个不需要 tun，也不需要 sudo

![Uploading image.png…]()

**Comment by aurorax-neo** [comment]
> #141 实现了一个无 tun 模式。这个不需要 tun，也不需要 sudo
> 
> ![D8FBFB867D8D00CB7117D74D604D3DA2](https://private-user-images.githubusercontent.com/5665404/337990964-38d283df-7ea6-491f-823d-6a19a344566c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTU2NzEsIm5iZiI6MTcxNzk5NTM3MSwicGF0aCI6Ii81NjY1NDA0LzMzNzk5MDk2NC0zOGQyODNkZi03ZWE2LTQ5MWYtODIzZC02YTE5YTM0NDU2NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMDQ1NjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ0N2U0ZjdlZjFhMTRjNjc2NzhjYzM2OGY5NTU5YWY1YzVjYTVjMzRhZmJlODNmNDNhZDgxYTUwNDgwOTA1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8lTG8zhqu5RvTTQm-856YzpTsBQalCHoHB-UYnO6ck8)

谢谢，我去试一试

**Comment by aurorax-neo** [comment]
请问能否编译一份 freebsd 的release？

**Comment by KKRainbow** [comment]
> 请问能否编译一份 freebsd 的release？

freebsd 上可以直接 cargo install 不？

**Comment by aurorax-neo** [comment]
> > 请问能否编译一份 freebsd 的release？
> 
> freebsd 上可以直接 cargo install 不？

机器没权限  只能运行二进制

**Comment by KKRainbow** [comment]
> > > 请问能否编译一份 freebsd 的release？
> > 
> > 
> > freebsd 上可以直接 cargo install 不？
> 
> 机器没权限 只能运行二进制

cargo install 不需要 root 权限

**Comment by aurorax-neo** [comment]
> > > > 请问能否编译一份 freebsd 的release？
> > > 
> > > 
> > > freebsd 上可以直接 cargo install 不？
> > 
> > 
> > 机器没权限 只能运行二进制
> 
> cargo install 不需要 root 权限

pkg的权限都没有，弄不上cargo，实在是 搞不定rust

**Comment by KKRainbow** [comment]
[easytier-bsd.zip](https://github.com/user-attachments/files/15775633/easytier-bsd.zip)

我在 FreeBSD 14.1-RELEASE 上编译的，去掉了 tun 依赖。帮忙试试能不能用

**Comment by aurorax-neo** [comment]
> [easytier-bsd.zip](https://github.com/user-attachments/files/15775633/easytier-bsd.zip)
> 
> 我在 FreeBSD 14.1-RELEASE 上编译的，去掉了 tun 依赖。帮忙试试能不能用

报错  这个
![image](https://github.com/EasyTier/EasyTier/assets/83893968/c67d7b4b-dd23-49be-8033-dd5c50a65f9c)

**Comment by KKRainbow** [comment]
> > [easytier-bsd.zip](https://github.com/user-attachments/files/15775633/easytier-bsd.zip)
> > 我在 FreeBSD 14.1-RELEASE 上编译的，去掉了 tun 依赖。帮忙试试能不能用
> 
> 报错 这个 ![image](https://private-user-images.githubusercontent.com/83893968/338444675-c67d7b4b-dd23-49be-8033-dd5c50a65f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk4MTcsIm5iZiI6MTcxODA4OTUxNywicGF0aCI6Ii84Mzg5Mzk2OC8zMzg0NDQ2NzUtYzY3ZDdiNGItZGQyMy00OWJlLTgwMzMtZGQ1YzUwYTY1ZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzU1YzczOTVjODgxOTQ1MzdiNmJiYmRlNTQ4NjM1YWUxNWE1MTYxN2ZiZWIxODY1NjY2MmVhZjU0ZmY3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzt4ni2Rqdyn-x8SzxT80KKNPyExRU9Orcg3tFGdt7E)

你用的什么版本的 freebsd。这个报错是因为我的编译机太新了

**Comment by aurorax-neo** [comment]
> > > [easytier-bsd.zip](https://github.com/user-attachments/files/15775633/easytier-bsd.zip)
> > > 我在 FreeBSD 14.1-RELEASE 上编译的，去掉了 tun 依赖。帮忙试试能不能用
> > 
> > 
> > 报错 这个 ![image](https://private-user-images.githubusercontent.com/83893968/338444675-c67d7b4b-dd23-49be-8033-dd5c50a65f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk4MTcsIm5iZiI6MTcxODA4OTUxNywicGF0aCI6Ii84Mzg5Mzk2OC8zMzg0NDQ2NzUtYzY3ZDdiNGItZGQyMy00OWJlLTgwMzMtZGQ1YzUwYTY1ZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzU1YzczOTVjODgxOTQ1MzdiNmJiYmRlNTQ4NjM1YWUxNWE1MTYxN2ZiZWIxODY1NjY2MmVhZjU0ZmY3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzt4ni2Rqdyn-x8SzxT80KKNPyExRU9Orcg3tFGdt7E)
> 
> 你用的什么版本的 freebsd。这个报错是因为我的编译机太新了

![image](https://github.com/EasyTier/EasyTier/assets/83893968/b278ad8b-e8eb-4d4e-ab96-f3f3e84c3774)

这个版本

**Comment by KKRainbow** [comment]
我装个 13.2 编译试试

**Comment by KKRainbow** [comment]
[easytier.zip](https://github.com/user-attachments/files/15807335/easytier.zip)

13.2 上编译的

**Comment by aurorax-neo** [comment]
> [easytier.zip](https://github.com/user-attachments/files/15807335/easytier.zip)
> 
> 13.2 上编译的

可以运行 感谢🙏

**Comment by KKRainbow** [comment]
好的，那这个问题我关了。有问题可以提新的 issue
