### ISSUE TITLE
链接意外断开

### ISSUE THREAD

**Issue by assassinliujie** [EasyTier/EasyTier#125]
网络结构如下 A 公网 B双网卡母机 C,D母机中其中一张网卡的虚拟机。
B,C,D直接连到A
AD为ubuntu系统 BC为windows系统
其中C机的连接经常断开，需要在GUI上点击断开在重新连接才能生效。但是此时在所有机器的GUI上都认为C机在线，而A机pingC机不通，A机上的nginx转发C机的虚拟局域网IP至80，该服务也不可用。
同时D机上的服务通过A机nginx转发内网IP端口之后工作异常，可以加载出页面来但是进一步不工作。
之前使用wireguard的时候不存在这种问题。请问如何解决

**Comment by assassinliujie** [comment]
测试发现当B机访问C机上的服务并且失败后，A机转发到公网随即失效。请问是否是某种冲突。

**Comment by assassinliujie** [comment]
> 用的是 release 版本么？那个版本设置的 mtu 有问题，可能会导致你说的 web 无法加载的问题。
> 
> C 机链接断开的频率是多少？release 上有另外一个 bug，会导致断开后不自动重连，另外 C 和 A 的 ping 延迟是多少？

你好，C机只会在B机尝试通过虚拟局域网地址访问之后断开。C和A延迟50ms

**Comment by assassinliujie** [comment]
> 用的是 release 版本么？那个版本设置的 mtu 有问题，可能会导致你说的 web 无法加载的问题。
> 
> C 机链接断开的频率是多少？release 上有另外一个 bug，会导致断开后不自动重连，另外 C 和 A 的 ping 延迟是多少？

另外有一个新的bug。A机用nginx反代B机上的jellyfin后，web可以正常打开，但是jellyfin media player却无法打开，非常奇怪的bug，但是之前使用wireguard或者frp没有出现类似的问题，也不知道是啥原因

**Comment by assassinliujie** [comment]
> 用的是 release 版本么？那个版本设置的 mtu 有问题，可能会导致你说的 web 无法加载的问题。
> 
> C 机链接断开的频率是多少？release 上有另外一个 bug，会导致断开后不自动重连，另外 C 和 A 的 ping 延迟是多少？

最近断联情况越来越频繁了，GUI界面上正常显示连接设备数，但是无法连接到机器，点断开再连接就又恢复。

**Comment by KKRainbow** [comment]
你现在用的是哪个版本

**Comment by assassinliujie** [comment]
> 你现在用的是哪个版本

还是使用的release V1.0.0

**Comment by KKRainbow** [comment]
命令行： https://github.com/EasyTier/EasyTier/actions/runs/9365589197
GUI: https://github.com/EasyTier/EasyTier/actions/runs/9365589196
可否用这个版本试一下。
之前群里也有人反馈断连，用了新的版本之后稳定很多了

**Comment by assassinliujie** [comment]
> 命令行： https://github.com/EasyTier/EasyTier/actions/runs/9365589197 GUI： https://github.com/EasyTier/EasyTier/actions/runs/9365589196 可否用这个版本试一下。 之前群里也有人反馈断连，用了新的版本之后稳定很多了

好的，我尝试一下

**Comment by KKRainbow** [comment]
现在还有个待验证的 bug。等那个 bug 解决之后就发 110 版本。

**Comment by KKRainbow** [comment]
请问下新版本还有断连的问题么，没有的话我就可以关闭这个 issue 了

**Comment by assassinliujie** [comment]
> 请问下新版本还有断连的问题么，没有的话我就可以关闭这个 issue 了

有

**Comment by assassinliujie** [comment]
> 请问下新版本还有断连的问题么，没有的话我就可以关闭这个 issue 了

在尝试过程中发现，公网机之间的连接连的上，但是非公网机和公网机之间全部 peer removed

**Comment by assassinliujie** [comment]
> 请问下新版本还有断连的问题么，没有的话我就可以关闭这个 issue 了

昨天只测试了公网机，今天尝试连入非公网机的时候发现不管是GUI还是命令行都不行了

**Comment by assassinliujie** [comment]
> 请问下新版本还有断连的问题么，没有的话我就可以关闭这个 issue 了

对于作为命令中的peers的那台公网机一侧只提示added，内网一侧对于公网机报removed，ping也ping不通

**Comment by KKRainbow** [comment]
请问下可否通过 IM 工具联系你，TG or QQ or WeChat？

**Comment by assassinliujie** [comment]
> 请问下可否通过 IM 工具联系你，TG or QQ or WeChat？

你好，tg 用户名@alizoed

**Comment by KKRainbow** [comment]
你在 tg 群么，可否加下 tg 群，我私聊你没法发消息

**Comment by KKRainbow** [comment]
你在 tg 群么，可否加下 tg 群，我私聊你没法发消息 
https://t.me/easytier

**Comment by assassinliujie** [comment]
> 你在 tg 群么，可否加下 tg 群，我私聊你没法发消息

好的，进群了

**Comment by KKRainbow** [comment]
这个问题看来可以关了？
主要是两个问题导致：
1. network_name 没保持一致，所以节点加入网络后看不到其他节点。
2. 虚拟 ip 不能分配 255，255 是广播地址。

你后面所说的无法重连，以及 win 上性能的问题，我会在
https://github.com/EasyTier/EasyTier/issues/140
这个 issue 中专项解决
