### ISSUE TITLE
能否增加armv7l架构CPU的编译版本

### ISSUE THREAD

**Issue by moreant** [EasyTier/EasyTier#126]

**Comment by lmq8267** [comment]
[easytier-linux-armv7l.zip](https://github.com/EasyTier/EasyTier/files/15484054/easytier-linux-armv7l.zip)

**Comment by moreant** [comment]
> [easytier-linux-armv7l.zip](https://github.com/EasyTier/EasyTier/files/15484054/easytier-linux-armv7l.zip)
> 
> [easytier-linux-arm.zip](https://github.com/EasyTier/EasyTier/files/15484112/easytier-linux-arm.zip)

感谢，不过还是希望仓库的 Release 里有，这样的话就能通过脚本来下载最新版的编译文件了。

**Comment by lmq8267** [comment]
下个版本发布的时候 作者就会全平台的了
