### ISSUE TITLE
无公网的客户端能否自动使用有公网的设备进行中转啊

### ISSUE THREAD

**Issue by kettly1260** [EasyTier/EasyTier#136]
如果部分设备是无公网的，但还有的设备是存在ipv6/v4 nat1，是否可以通过有公网的自设备进行流量中转呢

**Comment by KKRainbow** [comment]
现在的路由策略是：如果中转次数少就选中转最少得路径，如果中转次数一样，就选整体延迟最低的路径。
跟有无公网、nat 类型没有关系
