### ISSUE TITLE
丢包问题

### ISSUE THREAD

**Issue by ztzheng** [EasyTier/EasyTier#138]
非常感谢提供了这样一个项目！

两台局域网电脑使用公网节点，ping内网ip延迟低于2ms，不丢包
但是ping虚拟ip，丢包率超过10%

![Uploading Snipaste_2024-06-08_16-39-47.png…]()

**Comment by KKRainbow** [comment]
是 1.1.0 版本么

**Comment by KKRainbow** [comment]
节点间是通过什么协议连接的。udp ？

**Comment by ztzheng** [comment]
1.1.0版本，协议是tcp

**Comment by ztzheng** [comment]
> 节点间是通过什么协议连接的。udp ？

1.1.0版本，协议是tcp

**Comment by KKRainbow** [comment]
我看另外有老哥也报告的丢包问题，我仔细研究下原因

**Comment by KKRainbow** [comment]
可以提供一下你两个机器的配置信息么，什么操作系统。

我尝试了各种组合都复现不出来

**Comment by ztzheng** [comment]
> 可以提供一下你两个机器的配置信息么，什么操作系统。
> 
> 我尝试了各种组合都复现不出来

一台win10，一台win11，用11的ping 10那台

**Comment by KKRainbow** [comment]
方便联系下你，进到你的虚拟网测试下么。我复现不出来。

TG，qq, 微信都可以

**Comment by NianSan** [comment]
![图片](https://github.com/user-attachments/assets/c31ee90e-6bc8-401b-98d7-5c46122b4e5a)
同样丢包严重，一会自动断开
![图片](https://github.com/user-attachments/assets/25e0fe41-1f01-4046-87db-835010adc73e) @KKRainbow

**Comment by liuxiawei** [comment]
同样丢包严重，使用scoket协议连接，丢包率68%。
