### ISSUE TITLE
功能建议及win10自启动问题

### ISSUE THREAD

**Issue by yishengan** [EasyTier/EasyTier#143]
感谢大佬开发此项目！

win10自启动不能正常启动程序，任务管理器启动项有本程序的启动项，已在朋友电脑复现问题，我自己把程序添加到任务计划里正常启动。

建议添加静默启动，启动时不打开本程序ui窗口，只在任务栏显示。

**Comment by KKRainbow** [comment]
我调查一下，感谢反馈

**Comment by drzazi** [comment]
感谢你的付出，非常喜欢easytier。
但我的gui也不能自启动，在三台win 11 pro都复现了。尝试过界面上的自启动，加到自启动文件夹，计划任务，都不生效。因为这个原因还是不能替换掉zerotier
