### ISSUE TITLE
MacOS 10.15 GUI界面错乱

### ISSUE THREAD

**Issue by sbweiwei** [EasyTier/EasyTier#144]
![image](https://github.com/EasyTier/EasyTier/assets/12050042/ac4e983b-640b-407e-bba3-c1d248174702)

**Comment by KKRainbow** [comment]
怎么执行的，下载的dmg 还是自己编译的。如果是自己编译，需要执行 pnpm tauri build

**Comment by KKRainbow** [comment]
可能是 tauri 的锅，他说支持 mac >= 10.13，看来实际上有问题

我没这个版本的 os，没法测试验证

**Comment by KKRainbow** [comment]
要不先试试命令行版本吧，用起来也不复杂

**Comment by sbweiwei** [comment]
我回头试试命令行

之前1.0时候办公室的win10有段时间可以组网成功也能访问，配置应该没问题的。
但是后面突然就不行了，包括1.0和1.1，现在这个版本开dhcp功能不报错也能看到组网的另外一端信息，但是虚拟ipv4获取不出来也不能访问另一端。。
不开dhcp的话命令行报错

tun device ready. dev: et_6_aio3
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: ShellCommandError("无法完成此功能。\r\n\r\n\r\n")), location: Location { file: "easytier\\src/easytier-core.rs", line: 556, col: 22 }, can_unwind: true, force_no_backtrace: false }


现在我都不知道是哪里出了问题只能尝试搬出其他上古设备试🥲。

**Comment by KKRainbow** [comment]
后面突然不行，有可能是防火墙的原因，可以试试关闭防火墙

出现这个报错的时候，你用的启动命令是什么

**Comment by sbweiwei** [comment]
防火墙之前看了应该没问题。。
命令行和gui基本都用最简单的name和secret，服务器用public和自己的都不行，感觉不是防火墙问题，因为开了dhcp能看到自己的其他机器
![image](https://github.com/EasyTier/EasyTier/assets/12050042/e89ba794-939e-4251-b97d-99086efe7766)

相同网络和设置用win7跑是报这个
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::u
nwrap()` on an `Err` value: TunError(WintunError(String("Failed to create adapte
r")))), location: Location { file: "easytier\\src/easytier-core.rs", line: 556,
col: 22 }, can_unwind: true, force_no_backtrace: false }

**Comment by KKRainbow** [comment]
win7 要打补丁 https://www.youwindowsworld.com/en/downloads/operating-systems/windows-7/update-windows-7-kb4474419/

另外你的 virtual ip 是空的，好像 dhcp 没能成功分 ip，你手动分个 10.144.144.10 呢

**Comment by sbweiwei** [comment]
win7之前试了是打了补丁的，不过也先不纠结win7的了。。

问题就是我也发现不分配ip，但是关了dhcp的选项就会报错
![image](https://github.com/EasyTier/EasyTier/assets/12050042/7ff56ed2-4779-4976-bbec-8267a3b39aff)

**Comment by KKRainbow** [comment]
可以用命令行打开 log 试试么
--console-log-level info
看看具体是执行哪个命令报的错

**Comment by sbweiwei** [comment]
F:\easytier>easytier-core --ipv4 10.144.144.3 --peers wg://xxxxx:11011 --network-name aaaaa --network-secret aaaaa --console-log-level info

parsing listeners: ["11010"]

  [2m2024-06-13T10:09:59.2313909+08:00[0m [32m INFO[0m [1;32measytier_core::instance::instance[0m[32m: [32m[INIT] instance creating. config: instance_name = "default"

instance_id = "fd268b4b-b0da-4b90-9220-cb450cbf9851"

ipv4 = "10.144.144.3"

dhcp = false

listeners = [

    "tcp://0.0.0.0:11010",

    "udp://0.0.0.0:11010",

    "wg://0.0.0.0:11011",

    "ws://0.0.0.0:11011/",

    "wss://0.0.0.0:11012/",

]

exit_nodes = []

rpc_portal = "127.0.0.1:15888"



[network_identity]

network_name = "aaaaa"

network_secret = "aaaaa"



[[peer]]

uri = "wg://xxxxx:11011"



[console_logger]

level = "info"



[flags]

default_protocol = "tcp"

enable_encryption = true

enable_ipv6 = true

mtu = 1380

latency_first = false

enable_exit_node = false

[0m

    [2;3mat[0m easytier\src\instance\instance.rs:313



  [2m2024-06-13T10:09:59.2318043+08:00[0m [32m INFO[0m [1;32measytier_core::peers::peer_rpc[0m[32m: [32m[PEER RPC MGR] register service 1 succeed, my_node_id 1325191784[0m

    [2;3mat[0m easytier\src\peers\peer_rpc.rs:305



Starting easytier with config:

############### TOML ###############



instance_name = "default"

instance_id = "fd268b4b-b0da-4b90-9220-cb450cbf9851"

ipv4 = "10.144.144.3"

dhcp = false

listeners = [

    "tcp://0.0.0.0:11010",

    "udp://0.0.0.0:11010",

    "wg://0.0.0.0:11011",

    "ws://0.0.0.0:11011/",

    "wss://0.0.0.0:11012/",

]

exit_nodes = []

rpc_portal = "127.0.0.1:15888"



[network_identity]

network_name = "aaaaa"

network_secret = "aaaaa"



[[peer]]

uri = "wg://xxxxx:11011"



[console_logger]

level = "info"



[flags]

default_protocol = "tcp"

enable_encryption = true

enable_ipv6 = true

mtu = 1380

latency_first = false

enable_exit_node = false



-----------------------------------

  [2m2024-06-13T10:09:59.238285+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "ring", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("fd268b4b-b0da-4b90-9220-cb450cbf9851")), port: None, path: "", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2396147+08:00[0m [32m INFO[0m [1;32measytier_core::tunnel::ring[0m[32m: [32mlisten new conn of key: ring://fd268b4b-b0da-4b90-9220-cb450cbf9851[0m

    [2;3mat[0m easytier\src\tunnel\ring.rs:291



  [2m2024-06-13T10:09:59.2399771+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "tcp", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(11010), path: "", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2407651+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(11010), path: "", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2410047+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "wg", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(11011), path: "", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2412721+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "ws", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(0.0.0.0)), port: Some(11011), path: "/", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2417628+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "wss", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(0.0.0.0)), port: Some(11012), path: "/", query: None, fragment: None } } }, must_succ: true }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2420448+08:00[0m [33m WARN[0m [1;33measytier_core::instance::listeners[0m[33m: [33mrun listener: Listener { inner: Mutex { data: TunnelListener { local_url: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(::)), port: Some(0), path: "", query: None, fragment: None } } }, must_succ: false }[0m

    [2;3mat[0m easytier\src\instance\listeners.rs:174



  [2m2024-06-13T10:09:59.2424111+08:00[0m [32m INFO[0m [1;32measytier_core::peers::peer_rpc[0m[32m: [32m[PEER RPC MGR] register service 7 succeed, my_node_id 1325191784[0m

    [2;3mat[0m easytier\src\peers\peer_rpc.rs:305



  [2m2024-06-13T10:09:59.242505+08:00[0m [32m INFO[0m [1;32measytier_core::peers::peer_rpc[0m[32m: [32m[PEER RPC MGR] register service 1 succeed, my_node_id 1325191784[0m

    [2;3mat[0m easytier\src\peers\peer_rpc.rs:305



  [2m2024-06-13T10:09:59.2489169+08:00[0m [31mERROR[0m [1;31mwintun::log[0m[31m: [31mWinTun: Failed to find matching adapter name: 找不到元素。 (Code 0x00000490)[0m

    [2;3mat[0m C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wintun-0.3.2\src\log.rs:30



  [2m2024-06-13T10:09:59.3064407+08:00[0m [32m INFO[0m [1;32mwintun::log[0m[32m: [32mWinTun: Using existing driver 0.14[0m

    [2;3mat[0m C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wintun-0.3.2\src\log.rs:28



  [2m2024-06-13T10:09:59.3105407+08:00[0m [32m INFO[0m [1;32mwintun::log[0m[32m: [32mWinTun: Creating adapter[0m

    [2;3mat[0m C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wintun-0.3.2\src\log.rs:28



  [2m2024-06-13T10:09:59.4143672+08:00[0m [32m INFO[0m [1;32measytier_core::common::ifcfg[0m[32m: [32mInterface found, [1;32mname[0m[32m: "et_6_rjsq", [1;32midx[0m[32m: 31[0m

    [2;3mat[0m easytier\src\common\ifcfg.rs:363



  [2m2024-06-13T10:09:59.4179952+08:00[0m [33m WARN[0m [1;33measytier_core::connector::manual[0m[33m: [33mconn_mgr_routine started[0m

    [2;3mat[0m easytier\src\connector\manual.rs:166



  [2m2024-06-13T10:09:59.4206294+08:00[0m [32m INFO[0m [1;32measytier_core::tunnel::ring[0m[32m: [32mwaiting accept new conn of key: ring://fd268b4b-b0da-4b90-9220-cb450cbf9851[0m

    [2;3mat[0m easytier\src\tunnel\ring.rs:300

    [2;3min[0m easytier_core::instance::listeners::[1mrun_listener[0m [2;3mwith[0m [1mlistener[0m: Mutex { data: TunnelListener { local_url: Url { scheme: "ring", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("fd268b4b-b0da-4b90-9220-cb450cbf9851")), port: None, path: "", query: None, fragment: None } } }, [1mpeer_manager[0m: PeerManager { my_peer_id: 1325191784, instance_name: "default", net_ns: None }, [1mglobal_ctx[0m: GlobalCtx { inst_name: "default", id: fd268b4b-b0da-4b90-9220-cb450cbf9851, net_ns: None, event_bus: "EventBus", ipv4: AtomicCell { value: Some(10.144.144.3) } }



  [2m2024-06-13T10:09:59.4218794+08:00[0m [32m INFO[0m [1;32measytier_core::tunnel::udp[0m[32m: [32mstart udp accept: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(11010), path: "", query: None, fragment: None }[0m

    [2;3mat[0m easytier\src\tunnel\udp.rs:426

    [2;3min[0m easytier_core::instance::listeners::[1mrun_listener[0m [2;3mwith[0m [1mlistener[0m: Mutex { data: TunnelListener { local_url: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(11010), path: "", query: None, fragment: None } } }, [1mpeer_manager[0m: PeerManager { my_peer_id: 1325191784, instance_name: "default", net_ns: None }, [1mglobal_ctx[0m: GlobalCtx { inst_name: "default", id: fd268b4b-b0da-4b90-9220-cb450cbf9851, net_ns: None, event_bus: "EventBus", ipv4: AtomicCell { value: Some(10.144.144.3) } }



  [2m2024-06-13T10:09:59.4222191+08:00[0m [32m INFO[0m [1;32measytier_core::tunnel::udp[0m[32m: [32mstart udp accept: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(::)), port: Some(54221), path: "", query: None, fragment: None }[0m

    [2;3mat[0m easytier\src\tunnel\udp.rs:426

    [2;3min[0m easytier_core::instance::listeners::[1mrun_listener[0m [2;3mwith[0m [1mlistener[0m: Mutex { data: TunnelListener { local_url: Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(::)), port: Some(54221), path: "", query: None, fragment: None } } }, [1mpeer_manager[0m: PeerManager { my_peer_id: 1325191784, instance_name: "default", net_ns: None }, [1mglobal_ctx[0m: GlobalCtx { inst_name: "default", id: fd268b4b-b0da-4b90-9220-cb450cbf9851, net_ns: None, event_bus: "EventBus", ipv4: AtomicCell { value: Some(10.144.144.3) } }



2024-06-13 10:09:59: new listener added. listener: tcp://0.0.0.0:11010

2024-06-13 10:09:59: new listener added. listener: udp://0.0.0.0:11010

2024-06-13 10:09:59: new listener added. listener: wg://0.0.0.0:11011

2024-06-13 10:09:59: new listener added. listener: ws://0.0.0.0:11011/

2024-06-13 10:09:59: new listener added. listener: wss://0.0.0.0:11012/

2024-06-13 10:09:59: new listener added. listener: udp://[::]:54221

  [2m2024-06-13T10:09:59.4396406+08:00[0m [32m INFO[0m [1;32measytier_core::common::stun[0m[32m: [32mstart stun packet listener[0m

    [2;3mat[0m easytier\src\common\stun.rs:306

    [2;3min[0m easytier_core::common::stun::[1mstun_packet_listener[0m

    [2;3min[0m easytier_core::common::stun::[1mdetect_nat_type_with_socket[0m [2;3mwith[0m [1mudp[0m: PollEvented { io: Some(UdpSocket { addr: 0.0.0.0:54223, socket: 992 }) }



  [2m2024-06-13T10:09:59.530238+08:00[0m [32m INFO[0m [1;32measytier_core::common::ifcfg[0m[32m: [32mrun shell cmd, [1;32mcmd[0m[32m: "netsh interface ipv4 set subinterface et_6_rjsq mtu=1360", [1;32mec[0m[32m: Some(0), [1;32msucc[0m[32m: true, [1;32mstdout[0m[32m: "确定。\r\n\r\n", [1;32mstderr[0m[32m: ""[0m

    [2;3mat[0m easytier\src\common\ifcfg.rs:79



2024-06-13 10:09:59: tun device ready. dev: et_6_rjsq

  [2m2024-06-13T10:09:59.5323665+08:00[0m [32m INFO[0m [1;32measytier_core::peers::peer_ospf_route[0m[32m: [32mglobal event received in update_my_peer_info_routine, [1;32mev[0m[32m: Ok(TunDeviceReady("et_6_rjsq"))[0m

    [2;3mat[0m easytier\src\peers\peer_ospf_route.rs:1354

    [2;3min[0m easytier_core::peers::peer_ospf_route::[1mupdate_my_peer_info_routine[0m [2;3mwith[0m [1mservice_impl[0m: PeerRouteServiceImpl { my_peer_id: 1325191784, sessions: [] }



  [2m2024-06-13T10:09:59.6209275+08:00[0m [32m INFO[0m [1;32measytier_core::instance::instance[0m[32m: [32m[USER_PACKET] not ipv4 packet: Ipv4Packet { version : 6, header_length : 0, dscp : 0, ecn : 0, total_length : 0, identification : 24, flags : 1, fragment_offset : 6911, ttl : 0, next_level_protocol : IpNextHeaderProtocol(0), checksum : 0, source : 0.0.0.0, destination : 0.0.0.0, options : [],  }[0m

    [2;3mat[0m easytier\src\instance\instance.rs:122



  [2m2024-06-13T10:09:59.6211121+08:00[0m [32m INFO[0m [1;32measytier_core::instance::instance[0m[32m: [32m[USER_PACKET] not ipv4 packet: Ipv4Packet { version : 6, header_length : 0, dscp : 0, ecn : 0, total_length : 0, identification : 8, flags : 1, fragment_offset : 6911, ttl : 254, next_level_protocol : IpNextHeaderProtocol(128), checksum : 0, source : 0.0.0.0, destination : 34.54.241.49, options : [],  }[0m

    [2;3mat[0m easytier\src\instance\instance.rs:122



  [2m2024-06-13T10:09:59.6222588+08:00[0m [32m INFO[0m [1;32measytier_core::instance::instance[0m[32m: [32m[USER_PACKET] not ipv4 packet: Ipv4Packet { version : 6, header_length : 0, dscp : 0, ecn : 0, total_length : 0, identification : 36, flags : 0, fragment_offset : 1, ttl : 254, next_level_protocol : IpNextHeaderProtocol(128), checksum : 0, source : 0.0.0.0, destination : 34.54.241.49, options : [],  }[0m

    [2;3mat[0m easytier\src\instance\instance.rs:122



  [2m2024-06-13T10:09:59.6786139+08:00[0m [32m INFO[0m [1;32measytier_core::common::ifcfg[0m[32m: [32mrun shell cmd, [1;32mcmd[0m[32m: "netsh interface set interface et_6_rjsq enable", [1;32mec[0m[32m: Some(1), [1;32msucc[0m[32m: false, [1;32mstdout[0m[32m: "无法完成此功能。\r\n\r\n\r\n", [1;32mstderr[0m[32m: ""[0m

    [2;3mat[0m easytier\src\common\ifcfg.rs:79



panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: ShellCommandError("无法完成此功能。\r\n\r\n\r\n")), location: Location { file: "easytier\\src/easytier-core.rs", line: 556, col: 22 }, can_unwind: true, force_no_backtrace: false }

**Comment by sbweiwei** [comment]
电脑是一个板载网卡一个usb网卡，板载网卡共享了网络给usb网卡

**Comment by KKRainbow** [comment]
机器重启后也会这样么

**Comment by sbweiwei** [comment]
是的，1.0的时候除了开始能正常使用一段时间，后面包括1.1都没有改动配置但是开始报错了。。

**Comment by sbweiwei** [comment]
只要加了--ipv4就会报错，不加能跑但是没有分配虚拟 ip 也没用

**Comment by sbweiwei** [comment]
另外请教下 wireguard 怎么配置。是 vpn portal 分配另外一个不冲突的网段，后面 22022 不用改吗？然后 生成的config需要手动改吗？

例如 软件生成的这段 config：
[Interface]
PrivateKey = AUxxxxVfJ6IMqmvoVaA1iR4=
Address = 10.11.12.0/32 # should assign an ip from this cidr manually

[Peer]
PublicKey = ItyxtxxxxM24D8ZMmC8Ln+YKy2hE=
AllowedIPs = 10.10.11.0/24,10.11.12.0/24
Endpoint = 0.0.0.0:22022 # should be the public ip(or domain) of the vpn server
PersistentKeepalive = 25

Address 是要改成10.11.12. 1/32这样？
Endpoint是要自己手动改成如easytier.public.kkrainbow.top：22022 这样的 public 服务器吗？

**Comment by KKRainbow** [comment]
> Address 是要改成10.11.12. 1/32这样？
是的 

> Endpoint是要自己手动改成如easytier.public.kkrainbow.top：22022 这样的 public 服务器吗？
Endpoint 要填你自己的开启了 vpn portal 的服务器的 ip 地址

**Comment by KKRainbow** [comment]
> 只要加了--ipv4就会报错，不加能跑但是没有分配虚拟 ip 也没用

可以发一下你 win 的详细版本信息么

**Comment by sbweiwei** [comment]
> > 只要加了--ipv4就会报错，不加能跑但是没有分配虚拟 ip 也没用
> 
> 
> 
> 可以发一下你 win 的详细版本信息么
> 
> 

![image](https://github.com/EasyTier/EasyTier/assets/12050042/dde0659e-6bd7-429f-9507-1aa8bae86f45)
不过感觉应该和版本关联不大，毕竟一开始是可以用的。但是不能用是不是我加了网卡之后不太记得了，不过尝试过拔了网卡好像也不行

**Comment by sbweiwei** [comment]
> > Address 是要改成10.11.12. 1/32这样？
> 
> 
> 
> 是的 
> 
> 
> 
> > Endpoint是要自己手动改成如easytier.public.kkrainbow.top：22022 这样的 public 服务器吗？
> 
> 
> 
> Endpoint 要填你自己的开启了 vpn portal 的服务器的 ip 地址
> 
> 

主要没有搞懂vpn portal后面那个22022是端口吗？是需要路由器把这个端口也映射出去吗？命令行的example是用11010所以有点搞不清

**Comment by KKRainbow** [comment]
> 主要没有搞懂vpn portal后面那个22022是端口吗？是需要路由器把这个端口也映射出去吗？命令行的example是用11010所以有点搞不清

嗯，这个需要映射出去，wireguard client 才能访问到

**Comment by KKRainbow** [comment]
> 不过感觉应该和版本关联不大，毕竟一开始是可以用的。但是不能用是不是我加了网卡之后不太记得了，不过尝试过拔了网卡好像也不行

不知道有没有机会让我远程下你这个机器，我看看能不能定位出问题

**Comment by sbweiwei** [comment]
> > 不过感觉应该和版本关联不大，毕竟一开始是可以用的。但是不能用是不是我加了网卡之后不太记得了，不过尝试过拔了网卡好像也不行
> 
> 
> 
> 不知道有没有机会让我远程下你这个机器，我看看能不能定位出问题

远程倒无问题，不过公司的电脑不太方便用那些知名的远程连接软件，但是这个又连接不上。
我在想会不会是端口问题，我换个端口试试。是用--listeners还是--default-protocal来改11010端口？

**Comment by sbweiwei** [comment]
> > 不过感觉应该和版本关联不大，毕竟一开始是可以用的。但是不能用是不是我加了网卡之后不太记得了，不过尝试过拔了网卡好像也不行
> 
> 
> 
> 不知道有没有机会让我远程下你这个机器，我看看能不能定位出问题

还是说我这边怎么测试给你结果？本机用dhcp选项不设置虚拟ip就能看到节点主机但是没有分配出ip，设置ip就不行。
节点主机现在用手机wireguard连接使用无问题。节点主机参数应该没有问题吧？

**Comment by KKRainbow** [comment]
怀疑可能跟添加了太多网卡配置有关系。master 分支合入了可以清理网卡注册表配置的补丁，可能可以解决你这个问题

**Comment by KKRainbow** [comment]
试试 v1.2.0，加入了注册表清理

**Comment by sbweiwei** [comment]
> 试试 v1.2.0，加入了注册表清理

用1.2.1 win gui版本，win10系统。dhcp不报错但是依然没有ip能获取。手动设置ip还是shell command error。

**Comment by sbweiwei** [comment]
> 试试 v1.2.0，加入了注册表清理

我保存了log不知道怎么上传🥲

**Comment by KKRainbow** [comment]
> > 试试 v1.2.0，加入了注册表清理
> 
> 我保存了log不知道怎么上传🥲

可以邮件发给我不，profile 里有邮箱

**Comment by sbweiwei** [comment]
> > > 试试 v1.2.0，加入了注册表清理
> 
> > 
> 
> > 我保存了log不知道怎么上传🥲
> 
> 
> 
> 可以邮件发给我不，profile 里有邮箱

回报一下，最新gui版本win7（用win10电脑共享出来的网络）已经能连上了，但是win10那个还是不能获取virtual ip，前几天发了个log去你邮箱了，你看看有没有帮助
