### ISSUE TITLE
子网配置问题

### ISSUE THREAD

**Issue by yaming116** [EasyTier/EasyTier#145]
感谢作者开发这么好的软件，有个问题请教一下：
如果组网的多个节点里面都开放了子网，子网有的ip段是一样的，可以指定路由规则访问哪个子网吗？

**Comment by KKRainbow** [comment]
现在没办法诶。可以加个功能允许节点手动指定路由规则，类似于
192.168.1.0/24 就从节点 A 转发这样的

**Comment by yaming116** [comment]
好的，感谢。 
还有一个问题，组网服务支持token之类的验证吗？目前可以设置的参数只是组网隔离，服务实际是对外完全开放的

**Comment by KKRainbow** [comment]
下个版本会加上

**Comment by husanpao** [comment]
请教下  我们网络环境是有一个大的局域网。
我假设这里有个服务器10.134.156.123 部署了节点
然后我们开发网络是一个小型的局域网，对外是一个ip10.134.156.100 ，我在这个小型的局域网部署了一个节点192.168.10.7，然后peer 指定10.134.156.123  -n 指定我们开发局域网 192.168.10.0/24

但是我现在在10.134.156.123看route 是存在192.168.10.0/24的。ping可以通，但是telnet啥的就不通了，小型局域网中起的web服务也打不开

**Comment by KKRainbow** [comment]
检查下做代理的机器上的防火墙

**Comment by xiaoqiqiya** [comment]
> 请教下 我们网络环境是有一个大的局域网。 我假设这里有个服务器10.134.156.123 部署了节点 然后我们开发网络是一个小型的局域网，对外是一个ip10.134.156.100 ，我在这个小型的局域网部署了一个节点192.168.10.7，然后peer 指定10.134.156.123 -n 指定我们开发局域网 192.168.10.0/24
> 
> 但是我现在在10.134.156.123看route 是存在192.168.10.0/24的。ping可以通，但是telnet啥的就不通了，小型局域网中起的web服务也打不开

我也出现这种问题了，防火墙也开了

**Comment by KKRainbow** [comment]
可以试试 v1.2.0 的 --use-smoltcp，这个不会被防火墙影响
