### ISSUE TITLE
试用了3天，特意来反馈一下

### ISSUE THREAD

**Issue by sansam** [EasyTier/EasyTier#149]
我的使用场景：大陆多云多地域VPC互联。
最开始使用strongswan的IPSEC VPN组网，不支持自动组mesh，工作量巨大；
后来接触到headscale，选一个中心区域VPC部署headscale，其他地域的VPC部署tailscale，它的自动组网、发布路由功能非常适合我。但是有一个无法忍受的弊端：虽然支持UDP打洞，但是大陆的UDP远不如TCP来的实在。我这里200Mbps的带宽，UDP只能跑10Mbps。

最近了解到EasyTier，初步感受它与headscale类似。我的部署结构如下：

- 1台vps跑easytier，不分配IP地址，仅作为多个easytier互联的中心节点，可以在上面查看peer和route的情况，同时仅允许TCP连接
- 其他多台vps跑easytier，自动获取IP地址，发布子网（Subnet Proxy），不允许easytier之间p2p连接（通过安全组主动屏蔽UDP）。同时easytier作为该VPC的网关，通过配置路由表的方式，最终实现VPC之间的vps互联
- 该方案所有流量均需要通过中心节点中转，以牺牲双倍流量的代价换取高速的传输速度（TCP下跑满200Mbps带宽）

非常感谢作者开源如此优秀的作品，另外还有一点小小的建议，希望采纳：

- 增加p2p开关
- easytier-cli peer支持显示对端eth0 IP地址和公网IP地址
- 优化easytier-cli route显示输出，目前配置约10个子网，显示错位
- 子网（Subnet Proxy）冲突提醒

**Comment by KKRainbow** [comment]
感谢您的建议，这些建议都很合理，我会排期实现的
