### ISSUE TITLE
建议添加防火墙穿透功能

### ISSUE THREAD

**Issue by ie123610** [EasyTier/EasyTier#160]
建议添加防火墙穿透功能以使得在两个工作在防火墙后的节点可以相互连接
注意此处指的防火墙为一般的包过滤防火墙  **而非会修改端口的NAT（NAPT）**

在此情境下端口不会发生改变 所以相比一般NAPT穿透可能会更简单
不过其应该会检查TCP建立状态 所以我们只能使用UDP

可参考实现方法:
[BEP55](http://www.bittorrent.org/beps/bep_0055.html)
[[译] NAT 穿透是如何工作的：技术原理及企业级实践](http://arthurchiao.art/blog/how-nat-traversal-works-zh/#%E7%A9%BF%E9%80%8F%E6%96%B9%E6%A1%88%E4%B8%A4%E8%BE%B9%E5%90%8C%E6%97%B6%E4%B8%BB%E5%8A%A8%E5%BB%BA%E8%BF%9E%E5%9C%A8%E6%9C%AC%E5%9C%B0%E9%98%B2%E7%81%AB%E5%A2%99%E4%B8%BA%E5%AF%B9%E6%96%B9%E6%89%93%E5%BC%80%E4%B8%80%E4%B8%AA%E6%B4%9E)

**Comment by KKRainbow** [comment]
这种的 NAT 类型应该会被识别为 NO PAT，是可以穿透的
