### ISSUE TITLE
docker部署的该如何使用WireGuard

### ISSUE THREAD

**Issue by luoshan5261486** [EasyTier/EasyTier#161]
看了文档照着操作没办法获取PrivateKey 和Endpoint 
自己比较小白 确实没搞出来 作者方便的话能帮忙解答一下吗
辛苦了! 项目非常nice 另外这个有交流群之类的吗

**Comment by luoshan5261486** [comment]
打错了 是PrivateKey 和PublicKey

**Comment by KKRainbow** [comment]
docker exec xxx easytier-cli vpn-portal

**Comment by luoshan5261486** [comment]
感谢 已解决easytier-core参数要添加到编排command里面 再./easytier-clie vpn-portal就可以了
