### ISSUE TITLE
是否能实现代理功能？

### ISSUE THREAD

**Issue by husanpao** [EasyTier/EasyTier#163]
现状：虚拟网络内A、B 2台机器。现有C机器开放了某个端口只能B访问。A与B组网，是否能在B将C作为子网？然后实现A也能访问C的端口

**Comment by KKRainbow** [comment]
用子网代理就行。https://www.easytier.top/guide/network/point-to-networking.html

如果只想暴露单个节点，填 cidr 可以填 C 机器的 ip 比如 192.168.2.2/32

**Comment by husanpao** [comment]
不行哦。
A IP：10.134.156.183
B IP： 26.47.99.202
C IP：21.46.32.163
A B组网，但是C是三方机器，不是B的子网，且不能组网，且C只开放了B的访问权限。
请问我如何配置使得A能访问B？

**Comment by KKRainbow** [comment]
b节点配置子网代理 21.46.32.163/32

**Comment by xianyu11111** [comment]
> b节点配置子网代理 21.46.32.163/32

请问我用公网当作节点A，本地电脑当作节点B，并开放了子网，公网节点A可以ping通子网，但是外网还是访问不到怎么办呀

**Comment by KKRainbow** [comment]
这个一般是做代理的节点的防火墙问题。可以试试 v1.2.0 的 --use-smoltcp
