### ISSUE TITLE
虚拟网络中的节点的监听地址为公网时，有什么办法增加访问限制吗

### ISSUE THREAD

**Issue by 912988434** [EasyTier/EasyTier#164]
感觉只要虚拟网络中的节点的监听公网地址被泄漏了，别人就可以利用该公网节点地址加上--network-name -network-secret进行组网，这个有什么办法可以限制吗

**Comment by yaming116** [comment]
https://github.com/EasyTier/EasyTier/issues/145 作者说下个版本会加上

**Comment by david88558855** [comment]
如果强制认证：11012/wertr 这样带路径认证的同样起到作用 后面路径如果不对就加入不进去 光靠ip和端口加入不了 ，不过这个带路径的还没搞出来

**Comment by KKRainbow** [comment]
新增
