### ISSUE TITLE
群晖7.1.1 使用docker运行,在没有其它设备连接时，仍然占用上传带宽,最高能达几MB

### ISSUE THREAD

**Issue by perfect-001** [EasyTier/EasyTier#169]
使用的docker命令是
docker run -d \
  --name=easytier \
  --restart=always \
  --privileged \
  --memory=128m \
  --hostname=easytier\
  --network=host \
  -v /volume1/docker/easytier:/root \
  -e TZ=Asia/Shanghai \
easytier/easytier:latest \
-i  192.168.#.# --network-name "*####"   --network-secret "####,"   -e tcp://#####:11010 
<img width="224" alt="屏幕截图 2024-07-12 101643" src="https://github.com/user-attachments/assets/9b37a1e0-eda4-46c9-8b8e-867e2a238104">

**Comment by KKRainbow** [comment]
可以帮忙抓包看看么，可以抓出来给我我来分析。按理说流量开销不会这么大

**Comment by perfect-001** [comment]
> 可以帮忙抓包看看么，可以抓出来给我我来分析。按理说流量开销不会这么大

不好意思，不太会抓包，但是发现Windows下的流量也不正常
![image](https://github.com/user-attachments/assets/a54952e3-2eb2-486b-904b-f0e8092e3dbe)

**Comment by KKRainbow** [comment]
这是多久跑了14g流量。。。

**Comment by perfect-001** [comment]
> 这是多久跑了14g流量。。。

没有怎么使用的情况下，运行24小时的

在线设备：一台云服务器，一台Symmetric NAT设备，一台Port Restricted设备

过去一个星期跑的流量，大部分情况都是挂后台的：
![image](https://github.com/user-attachments/assets/00f8dd84-e985-4d99-8a44-6cde5897f55f)

**Comment by perfect-001** [comment]
Port Restricted网络下的设备会上传大量流量

**Comment by KKRainbow** [comment]
可能是打洞太激进了，跑这么多流量有点夸张，我计算下理论值
