### ISSUE TITLE
windows11在软件打开开机自启，但重启电脑无法自动启动

### ISSUE THREAD

**Issue by perfect-001** [EasyTier/EasyTier#170]

**Comment by perfect-001** [comment]
![image](https://github.com/user-attachments/assets/146e9110-7a55-4b29-b31d-213cdabe7513)
能在启动项中看到，但是不能正常启动

**Comment by YoRHazzz** [comment]
遇到了同样的问题。

**Comment by KKRainbow** [comment]
自启动测试的少，有空我调查下

**Comment by Chernfalin** [comment]
WIN 10 碰到同样问题，UI里面打开开机启动，创建快捷方式，创建系统任务都不能启动，只有手动点击启动能成功。
