### ISSUE TITLE
请问windows的gui能直接作为服务端吗？

### ISSUE THREAD

**Issue by lianganbin** [EasyTier/EasyTier#173]
请问windows的gui能直接作为服务端吗？
有一台常年开机的WINDOWS然后又有公网IP的

**Comment by KKRainbow** [comment]
可以，官方的公网服务器就是这么玩的

**Comment by lianganbin** [comment]
我的这台windows是在路由器后面的，我只需要给他映射11010的端口吗？还是要其他设置吗？服务端有什么特别的设置吗？我现在是几台机器都连上这台windows服务器，在windows服务器端显示跟各个端都是p2p状态，但是各个端之间显示relay（2）这个状态

**Comment by KKRainbow** [comment]
嗯，把随便某个监听的端口映射出去都可以。不需要做什么特殊的设置。
各个端之间显示 relay 说明没有打洞成功，可以检查下网络环境
