### ISSUE TITLE
Inquiry About TCP NAT Traversal Support in Easytier

### ISSUE THREAD

**Issue by InCerryGit** [EasyTier/EasyTier#175]
Hi Easytier Team,

I hope this message finds you well.

I am writing to inquire about the support for TCP NAT traversal in Easytier. We have been experiencing significant speed limitations with UDP due to restrictions imposed by certain ISPs. As a result, when using solutions like ZeroTier, we are only able to achieve speeds of a few hundred kilobytes per second.

Given these constraints, we are exploring alternatives that might offer better performance under such conditions. Could you please confirm whether Easytier supports TCP NAT traversal for penetrating through NATs?

Thank you very much for your assistance.

Best regards.

**Comment by KKRainbow** [comment]
TCP NAT traversal is more complicated than UDP and not supported currentyly
