### ISSUE TITLE
openwrt

### ISSUE THREAD

**Issue by yangbo1317** [EasyTier/EasyTier#176]
请问可否出一个openwrt的安装教程

**Comment by yangbo1317** [comment]
![Snipaste_2024-07-17_00-14-54](https://github.com/user-attachments/assets/29f44bc4-e2ef-49ae-8e17-96192e568b1d)

**Comment by KKRainbow** [comment]
你这个编译失败是因为没有装 protobuf

**Comment by yangbo1317** [comment]
谢谢，我已经通过二进制文件成功运行了

**Comment by lingjianrui** [comment]
能不能直接出一个 openwrt arm64 v8 的 luci 二进制包。

**Comment by lingjianrui** [comment]
玩这个 主流的人群都是 玩openwrt 的。
