### ISSUE TITLE
运行后提示rust tun error Failed to create adapter

### ISSUE THREAD

**Issue by lianganbin** [EasyTier/EasyTier#178]
windows gui
运行后提示rust tun error Failed to create adapter
我之前装过tailscale，我卸载tailscale后easytier也运行不起来了，重新卸载好多次都不行。

**Comment by lianganbin** [comment]
查阅了一圈感觉应该是卸载时wintun没卸干净，请问这个这个wintun怎么卸载干净啊！求助！

**Comment by KKRainbow** [comment]
不太了解 tailscale。easytier 的 wintun 是自己打包了 dll，可以看看 system32 里有没有 tailscale 残留的 wintun 动态库

**Comment by marekchen** [comment]
可以试试以管理员身份运行

**Comment by metorm** [comment]
我刚刚在我电脑上解决了，可以看看你的是不是同样的原因： https://www.weiran.ink/windows/fix-win-tun-device-install-failure.html
