### ISSUE TITLE
关于解析ipv6域名的功能

### ISSUE THREAD

**Issue by lianganbin** [EasyTier/EasyTier#181]
发现好像貌似解析不了IPV6的域名，希望能添加这个功能

**Comment by KKRainbow** [comment]
可以解析。如果不可以请提供错误日志和复线方法

**Comment by lianganbin** [comment]
我指的是IPV6是域名,我直接填写域名不行。要填写[]加IPV6的地址才行，如果域名是纯IPV6的，需要怎么填写呢？因为客户机都有IPV6所以想都用IPV6组网
