### ISSUE TITLE
easytier-gui编译出现两个托盘图标

### ISSUE THREAD

**Issue by xiaonian233** [EasyTier/EasyTier#186]
依据easytier-gui的README的操作。编译使用 
> **pnpm tauri build --target x86_64-pc-windows-msvc**
![image](https://github.com/user-attachments/assets/bf2de6fb-f750-4fe6-8daf-89ee24eb6171)

![image](https://github.com/user-attachments/assets/defa86b3-73ca-4f3c-b0dd-f4368747bf5f)
出现两个托盘图标一个有icon一个没有icon。代码是直接拉取最新，未做改动
update:release的1.1.0版本编译后正常

**Comment by KKRainbow** [comment]
tauri2 的托盘实现有 bug

**Comment by xiaonian233** [comment]
okok，支持老哥开发
