### ISSUE TITLE
如果域名是纯IPV6的

### ISSUE THREAD

**Issue by lianganbin** [EasyTier/EasyTier#189]
如果域名是纯IPV6的，我直接填写比如域名是demoan.demoan.top我直接填写tcp://demoan.demoan.top:11010或者udp://demoan.demoan.top:11010并不能成功解析的。我直接填写真实的IPV6地址是可以的。是不是还不能自动解析纯IPV6的域名

**Comment by radaig** [comment]
这个非常实用，的确是如果域名是IPV6的没法正常建立连接，希望能增加直接解析ipv6域名的功能。

**Comment by KKRainbow** [comment]
之前我测试过 AAAA 的域名，可能后面又出问题了。我研究下

**Comment by black560** [comment]
> 如果域名是纯IPV6的，我直接填写比如域名是demoan.demoan.top我直接填写tcp://demoan.demoan.top:11010或者udp://demoan.demoan.top:11010并不能成功解析的。我直接填写真实的IPV6地址是可以的。是不是还不能自动解析纯IPV6的域名

我今天也遇到了，后来解决了。我是后加入的端点没有设置ipv6默认路由导致的，无法ping通ipv6域名，运行程序时会报错，把路由加了即可。如先查看本地ipv6路由route -6，再写入你实际的网关地址ip -6 route add default dev eth0 via fe80::*****

**Comment by lianganbin** [comment]
> > 如果域名是纯IPV6的，我直接填写比如域名是demoan.demoan.top我直接填写tcp://demoan.demoan.top:11010或者udp://demoan.demoan.top:11010并不能成功解析的。我直接填写真实的IPV6地址是可以的。是不是还不能自动解析纯IPV6的域名
> 
> 我今天也遇到了，后来解决了。我是后加入的端点没有设置ipv6默认路由导致的，无法ping通ipv6域名，运行程序时会报错，把路由加了即可。如先查看本地ipv6路由route -6，再写入你实际的网关地址ip -6 route add default dev eth0 via fe80::*****

我的是能PING V6域名的，就是填域名就不行，也没报错，就是建立不成功，但是填写IPV6实际地址是完全可以的。

**Comment by lianganbin** [comment]
> 之前我测试过 AAAA 的域名，可能后面又出问题了。我研究下

有QQ交流群吗？我可以给你远程看我的环境看看到底什么情况

**Comment by KKRainbow** [comment]
> > 之前我测试过 AAAA 的域名，可能后面又出问题了。我研究下
> 
> 有QQ交流群吗？我可以给你远程看我的环境看看到底什么情况

README 里有

**Comment by KKRainbow** [comment]
看来是域名里有两个 ip，现在只会用第一个去连，我改成随机取了

**Comment by black560** [comment]
你解决了吗
















在 2024-08-04 19:30:57，"lianganbin" ***@***.***> 写道：

如果域名是纯IPV6的，我直接填写比如域名是demoan.demoan.top我直接填写tcp://demoan.demoan.top:11010或者udp://demoan.demoan.top:11010并不能成功解析的。我直接填写真实的IPV6地址是可以的。是不是还不能自动解析纯IPV6的域名

我今天也遇到了，后来解决了。我是后加入的端点没有设置ipv6默认路由导致的，无法ping通ipv6域名，运行程序时会报错，把路由加了即可。如先查看本地ipv6路由route -6，再写入你实际的网关地址ip -6 route add default dev eth0 via fe80::*****

我的是能PING V6域名的，就是填域名就不行，也没报错，就是建立不成功，但是填写IPV6实际地址是完全可以的。

**Comment by KKRainbow** [comment]
升级 1.2.2 试试
