### ISSUE TITLE
Does this project support udp over tcp encapsulation? 

### ISSUE THREAD

**Issue by vahobrsti** [EasyTier/EasyTier#190]
Hello team, 

I'm reading the docs and I can't seem to find my answer. Is udp over tcp encapsulation supported?

**Comment by KKRainbow** [comment]
tcp tunnel is supported which is literally ip over tcp.
i'm not sure the udp over tcp you said is something like udp2raw, if so it's not supported for now

**Comment by vahobrsti** [comment]
Yep. That's exactly what I mean. a project like udp2raw where you can pass udp over tcp tunnel. Thanks anyway. will close the issue then.
