### ISSUE TITLE
建议 ./easytier-cli peer 显示自己的ipv4

### ISSUE THREAD

**Issue by xtccc** [EasyTier/EasyTier#192]
我是通过点对网 组网的，
在子网的机器中使用 rpc远程查看网络信息
但是 ./easytier-cli peer 无法显示网关自己的ip,有时候就会比较难受 
例如：
![image](https://github.com/user-attachments/assets/8da1c94b-b14d-45e5-a5f6-8fb2bd67edb5)

网关的ip 是10.144.144.2 ,我总要想一下，

希望想tailscale status那样把所有的 ip 显示出来（自己组网的ip 10.144.144.x)

当然，也可以另加一个命令， 毕竟peer 有peer 的含义

具体实现 开发组来定义 

预期 easytier-cli 能显示所有自组网的ip

**Comment by m1m1sha** [comment]
合并 issue https://github.com/EasyTier/EasyTier/issues/311#issue-2511381034
