### ISSUE TITLE
Alpine 无法使用

### ISSUE THREAD

**Issue by Xl-513** [EasyTier/EasyTier#194]
运行报错 
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: TunError(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))), location: Location { file: "easytier/src/easytier-core.rs", line: 556, col: 22 }, can_unwind: true, force_no_backtrace: false }
 是Alpine 缺少某些依赖么？是否可有给一下指引？

**Comment by KKRainbow** [comment]
没配好 tun

**Comment by Xl-513** [comment]
alpine 需要如何配置 ？
