### ISSUE TITLE
建议添加强制中转选项

### ISSUE THREAD

**Issue by canronglan** [EasyTier/EasyTier#204]
我的应用场景是这样的，在新加坡和台湾都有vps，但是都是非大陆线路优化，国内访问我是通过香港腾讯云来做中转，之前用的是n2n，有个强制服务器中转的选项，但是n2n比较简单，而且有时候会抽风，没有easytier peer这样的节点列表，现在用了easytier后，节点在不在线一目了然，但是问题就在连接台湾的vps是p2p，延迟到了300多ms~非常想要个强制中转的的功能；
        另外，我在easytier-core 的帮助打印中发现个 --latency-first 这个选项，字面意思是延迟第一，但是帮助里写的是日志文件地址，是否有误？而--latency-first 是否是智能路由里面以最低延迟路由为优先选择，然后做各种中转？

**Comment by KKRainbow** [comment]
--latency-first 会选择整体整体最低的路径，命令注释有误
理论上你的场景使用 latency-first 就可以解决

**Comment by canronglan** [comment]
好的，我说注释怎么变成了日志文件~

**Comment by canronglan** [comment]
另外问一下，easytier-gui，能否把这个--latency-first选项加上，或者添加个可选参数输入框？
