### ISSUE TITLE
一些端口建议

### ISSUE THREAD

**Issue by black560** [EasyTier/EasyTier#205]
使用环境：仅用IPv6互联的情况，初次使用讲的不对请包涵

1.第1台机器启动参数中只写了监听tcp端口如--listeners tcp://[::]:10001，但是启动后仍然开启了udp的随机端口监听udp://[::]:35465
后加入机器即使用了--no-listener，也会开启udp随机端口监听。

2.后加入的机器（第2台）启动的连接端口（未开监听端口）是随机的，防火墙出站端口得全放开，是固定端口好还是现在这种模式好，有待讨论。

3.rpc_portal没有找到关闭的命令行参数，导致系统多开一个端口，这个参数有什么用，网页端查看配置文件吗

**Comment by KKRainbow** [comment]
1. ipv6 的 udp 监听需要通过 --disable-ipv6 关闭
2. 如果未监听端口，走的是随机端口打洞
3. 这个参数是让 easytier-cli 访问的
