### ISSUE TITLE
Is the NAT detection mechanism too aggressive?

### ISSUE THREAD

**Issue by zhufengme** [EasyTier/EasyTier#226]
I often see over 100,000 connections, and today it caused the router to run slowly and the package to drop.

 Is it possible to customize the policy?

**Comment by KKRainbow** [comment]
are these connections udp or tcp? could you please take me a screenshot of netstat or ss

**Comment by zhufengme** [comment]
It looks like there are a lot of UDP connections. I have just taken the peer offline.

 If needed, I can restore it later and provide screenshots.

**Comment by zhufengme** [comment]
Screenshots have been sent via email.

**Comment by zhufengme** [comment]
I also found that the number of connections did not exceed what you mentioned. 

I will continue to monitor this and report when Recv-Q too high

Additionally, that can be observed is that this issue only occurs when there are multiple layers of NAT in the network.

**Comment by zhufengme** [comment]
Close this issue and reopen it after reproducing the problem.
