### ISSUE TITLE
Android设备无法访问OpenWRT节点代理的子网

### ISSUE THREAD

**Issue by HmnSn** [EasyTier/EasyTier#228]
节点部署在OpenWRT上，依次试了github actions的里生成的APK，从[fix crash on old version android (<= 9)](https://github.com/EasyTier/EasyTier/commit/fc9812dd545f9c2d352b7eacf95216ad569d4fe8)提交之后的Android客户端，想访问OpenWRT节点代理的子网会被OpenWRT的防火墙规则拦截，[fix vpn close when getting new subnet route](https://github.com/EasyTier/EasyTier/commit/8858492fb4f0012ed8a0b962e1b6228e2ee3e5fe)生成的APK能在同样防火墙规则下正常访问子网设备。Windows gui一直到最新版同样的启动参数都不受OpenWRT防火墙影响

**Comment by KKRainbow** [comment]
大哥牛逼，按照你的描述问题秒定位
<img width="1205" alt="image" src="https://github.com/user-attachments/assets/c2cdc31e-c4a9-48b0-b574-810f87925263">
