### ISSUE TITLE
--ipv4 parameter to support larger network ranges.

### ISSUE THREAD

**Issue by zhufengme** [EasyTier/EasyTier#238]
I noticed that #177 mentioned a related issue, but it was marked as "not planned." I propose reconsidering this feature.

1. My own project is currently facing an issue with the total number of nodes, as we are running a distributed network. There are over 1,000 nodes distributed across many locations.

2. Larger subnets would be more helpful for users to plan their own networks.

**Comment by KKRainbow** [comment]
In current version, peers in same virtual net will try to establish p2p connection to all other peers. if there are too many peers there will be a large amount of connections.

I think the expansion of virtual network range should be designed carefully, balancing between resource consuption and effiency.

I already have some ideas, e.g. icmp latency probe and lazily establish p2p conn. But i'm not sure if it's a high demand feature.

**Comment by zhufengme** [comment]
Thank you for your response. I understand your thoughts

Perhaps we can solve this by dividing the forwarding subnet. I look forward to your ideas.
