### ISSUE TITLE
建议添加手动指定下一跳路由的功能

### ISSUE THREAD

**Issue by canronglan** [EasyTier/EasyTier#240]
目前即使添加了 --latency-first 也会出现抽风的情况，而且只考虑了最低延迟路由，没考虑到丢包等问题，如果可以在easytier-cli 里的route功能中指定下一跳路由，这个对于有特殊指定路由的用户很有用。建议的命令行是这样 `easytier-cli route next ｛这里是下一跳路由的名称｝`例如`easytier-cli route next node1`

**Comment by KKRainbow** [comment]
如果支持禁用 p2p，可否支持你这个场景。所有的流量都只会经过 --peers 参数指定的节点

**Comment by KKRainbow** [comment]
https://github.com/EasyTier/EasyTier/pull/241
