### ISSUE TITLE
在easytier-cli peer中可以看到另外一个节点，但是却ping不通

### ISSUE THREAD

**Issue by lvzhaoxing** [EasyTier/EasyTier#242]
<img width="989" alt="image" src="https://github.com/user-attachments/assets/35e2628d-e0c5-4f27-a89f-3f184aab3314">

easytier-core -i 10.118.1.100 --network-name test --network-secret test -e tcp://easytier.public.kkrainbow.top:11010

easytier-core -i 10.118.100.3 --network-name test --network-secret test -e tcp://easytier.public.kkrainbow.top:11010

**Comment by lvzhaoxing** [comment]
<img width="809" alt="image" src="https://github.com/user-attachments/assets/6e656a5f-55f9-4e4f-b2af-244c792d4084">

**Comment by assassinliujie** [comment]
先确认是不是防火墙禁ping之类的

**Comment by KKRainbow** [comment]
你这都不在一个 /24 的子网里，当然 ping 不通。

**Comment by lvzhaoxing** [comment]
@KKRainbow 在一个 /24 的子网里的IP要怎么设置呢？

**Comment by KKRainbow** [comment]
在一个 /24 的子网中，意味着网络地址占用了24位，剩下的8位用于主机地址。这意味着每个 /24 子网可以有 2^(32-24) = 2^8 = 256 个可能的IP地址。然而，在这256个地址中，有两个地址是特殊的：

1. 网络地址：子网的第一个地址，通常用于标识网络本身，例如 192.168.1.0。
2. 广播地址：子网的最后一个地址，用于发送到该子网所有主机的消息，例如 192.168.1.255。

因此，实际可用的IP地址数量是 256 - 2 = 254 个。

设置 /24 子网的IP地址通常遵循以下步骤：

1. **确定网络地址**：这是子网的起始地址，通常是子网号加上网络部分的最后一个数字，例如，如果子网号是192.168.1，那么网络地址就是192.168.1.0。

2. **确定可用的IP地址范围**：从网络地址的下一个地址开始（例如，192.168.1.1），直到广播地址的前一个地址（例如，192.168.1.254）。

3. **设置子网掩码**：对于 /24 子网，子网掩码是 255.255.255.0。这表示前24位是网络部分，后8位是主机部分。

4. **配置默认网关**：这通常是网络地址的下一个地址，例如，如果网络地址是192.168.1.0，那么默认网关可能是192.168.1.1。

5. **配置DNS服务器**：这可以是ISP提供的DNS服务器地址，或者是内部DNS服务器的地址。

6. **配置其他网络设置**：根据需要配置其他网络参数，如WINS服务器地址、MTU大小等。

在配置IP地址时，确保不要使用网络地址和广播地址作为主机地址，并且避免IP地址冲突。通常，网络管理员会使用IP地址管理工具来跟踪和管理IP地址分配，以确保地址的唯一性和有效性。

**Comment by lvzhaoxing** [comment]
@KKRainbow 不好意思，问错了，如果想要16子网，子网掩码是 255.255.0.0，在EasyTier中要怎么设置呢。刚从n2n转过来，n2n中ip直接设置成10.118.100.3/16就行，但EasyTier好像不支持这样设置。

**Comment by KKRainbow** [comment]
嗯，et当前只支持24子网

**Comment by lvzhaoxing** [comment]
好的，谢谢
