### ISSUE TITLE
希望文档中新增对-c的config文件的范例及说明

### ISSUE THREAD

**Issue by lvzhaoxing** [EasyTier/EasyTier#245]
如题

**Comment by KKRainbow** [comment]
如果愿意可以辛苦帮忙提pr改一下

**Comment by bh1xaq** [comment]
[关联 easytier.github.io/pull/29 ](https://github.com/EasyTier/easytier.github.io/pull/29)

**Comment by lvzhaoxing** [comment]
官方文档已经更新 https://www.easytier.top/guide/network/config-file.html
