### ISSUE TITLE
这玩意能实现socks代理吗？

### ISSUE THREAD

**Issue by aohanhongzhi** [EasyTier/EasyTier#260]
不适用局域网，就两个不同地方的电脑，一个使用另一个的网络上网，实现socks代理。

**Comment by KKRainbow** [comment]
和你直接开个 socks5 server 有什么区别？

**Comment by aohanhongzhi** [comment]
> 和你直接开个 socks5 server 有什么区别？

母鸡啊，这个感觉就是把一个电脑，和不是当前的另一个局域网组在一起。实现自己到了另一个局域网。
比如，人在外地，访问家里的NAS啥的。

**Comment by KKRainbow** [comment]
easytier 是这样啊，就是异地组局域网，可以通过打洞来提高通信效率。
你说的 socks 代理具体指什么，是在虚拟网里用 socks5 吗，还是问这个跟 socks5 有啥区别？

**Comment by aohanhongzhi** [comment]
> easytier 是这样啊，就是异地组局域网，可以通过打洞来提高通信效率。 你说的 socks 代理具体指什么，是在虚拟网里用 socks5 吗，还是问 easytier 跟 socks5 有啥区别？

理解了，比如，可以打洞查看家里的本地服务，NAS，内网摄像头，内网服务器啥的。
那应该也可以直接连接windows远程桌面吧？

我就想想知道这玩意能不能实现socks5代理？从从而实现爬虫的ip代理池。

**Comment by KKRainbow** [comment]
> 那应该也可以直接连接windows远程桌面吧？
可以

> 我就想想知道这玩意能不能实现socks5代理？从从而实现爬虫的ip代理池。
正在做类似 tailscale 的 socks5 功能，但怕是跟你想要的不一样

**Comment by aohanhongzhi** [comment]
> > 那应该也可以直接连接windows远程桌面吧？
> 
> 可以
> 
> > 我就想想知道这玩意能不能实现socks5代理？从从而实现爬虫的ip代理池。
> 
> 正在做类似 tailscale 的 socks5 功能，但怕是跟你想要的不一样

不能实现ip代理，只是用socks5协议穿透组网？还是本地局域网？

**Comment by KKRainbow** [comment]
你可以先看看 tailscale 的文档。把 easytier 理解成不需要中心服务器的 tailscale 就好了
