### ISSUE TITLE
为什么连上了ping不通，请求大神帮解答

### ISSUE THREAD

**Issue by jayjay321** [EasyTier/EasyTier#270]
为什么连上了ping不通，请求大神帮解答
ping开着的
![微信截图_20240821115224](https://github.com/user-attachments/assets/0777fd92-f9fd-4184-bd44-87d9d4689f08)

**Comment by KKRainbow** [comment]
检查防火墙

**Comment by jayjay321** [comment]
防火墙是关闭的 @KKRainbow

**Comment by KKRainbow** [comment]
tcp / udp 通吗

**Comment by jayjay321** [comment]
@KKRainbow 不好意思  我的防火墙关了，原来对方的没关。关了就正常  谢谢
