### ISSUE TITLE
目前windows7下程序会crash，不知道是否支持该平台？

### ISSUE THREAD

**Issue by huangyongde** [EasyTier/EasyTier#272]
执行命令
easytier-core.exe --ipv4 xxxxx --network-name xxx --network-secret yyyy -e tcp://easytier.public.kkrainbow.top:11010
报错信息 
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	easytier-core.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	66ba3892
  故障模块名称:	wintun.dll
  故障模块版本:	0.14.1.0
  故障模块时间戳:	616ba8f7
  异常代码:	40000015
  异常偏移:	000000000000c51b
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0ac1
  其他信息 2:	0ac19e4db918b9fe6cb3602748e6055f
  其他信息 3:	5d1d
  其他信息 4:	5d1d511204019060c626ffa4104c8a1d

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by KKRainbow** [comment]
win7 需要是 SP1,并且需要安装 KB3063858、KB4474419 这两个补丁

**Comment by huangyongde** [comment]
谢谢，安装两个补丁以后正常使用了
