### ISSUE TITLE
已root安卓termux下能运行但是不能ping通虚拟局域网

### ISSUE THREAD

**Issue by canronglan** [EasyTier/EasyTier#274]
设备:红米K50U,已root，使用zerotermux

应用场景:由于有分应用科学上网的需求，VPN模式被占用，无法用easytier的app来启用easytier，想到用termux的sudo模式来启用easytier,由于安卓的tun接口位置(`/dev/tun`)和linux(`/dev/net/tun`)不同，又通过手动建立tun
```
sudo mkdir -p /dev/net
sudo mknod /dev/net/tun c 10 200
sudo chmod 600 /dev/net/tun
```
下载linux-aarch64版本的easytier
命令行用
`sudo /data/data/com.termux/files/home/easytier-linux-aarch64/easytier-core -i 192.168.124.30 --network-name xxxx --network-secret xxx --hostname k50u --dev-name easy0 -r 0.0.0.0:15888 -e udp://xxxxx:11015 -p udp://xxxxx:11010 -l udp://[::]:11010 tcp://[::]:11010 tcp://0.0.0.0:11010 udp://0.0.0.0:11010 wg://0.0.0.0:11011 wg://[::]:11011 >/dev/null 2>&1 &`
通过easytier-cli peer 可以查看虚拟局域网内所有的节点，但是无法ping通。

诡异的是另一台手机红米note7，root后同样操作就可以ping通，该如何排查？
补充一下：如果关闭科学上网的VPN，使用easytier的APP是可以正常链接的。

**Comment by KKRainbow** [comment]
ifconfig可以看到 easytier 的 tun设备上有 ip 吗。
另外 ip route 看下路由表项是否都成功添加了

**Comment by canronglan** [comment]
有的

**Comment by KKRainbow** [comment]
另外ping不通可能是防火墙，不知道手机上会有类似问题么。可以看看iptables规则，

**Comment by KKRainbow** [comment]
手机上有tcpdump么，抓下tun包看看呢

**Comment by canronglan** [comment]
sudo ip a
```
37: easy0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1360 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 192.168.124.30/24 scope global easy0
       valid_lft forever preferred_lft forever
```

sudo ip r

`192.168.124.0/24 dev easy0 proto kernel scope link src 192.168.124.30`

**Comment by canronglan** [comment]
好的，我试试tcpdump

**Comment by canronglan** [comment]
sudo tcpdump -i easy0 -w ~/tcpdump-easy0.dmp
```
tcpdump: listening on easy0, link-type RAW (Raw IP), snapshot length 262144 bytes


0 packets captured
0 packets received by filter
0 packets dropped by kernel
```
tcpdump直接没数据通过？

**Comment by KKRainbow** [comment]
是ping的时候做tcpdump么

**Comment by canronglan** [comment]
对的

**Comment by canronglan** [comment]
也用了easytier-cli peer，能看到所有peer，感觉是tun没生效？

**Comment by KKRainbow** [comment]
ping是从别的节点发起的，还是从tcpdump的手机发起的

**Comment by canronglan** [comment]
这台手机发起的

**Comment by canronglan** [comment]
如果用notun模式，如何访问其他的节点？

**Comment by KKRainbow** [comment]
1.2.2版本只能被访问，无法主动发起访问。即将发布的1.2.3可以通过socks5发起访问

**Comment by KKRainbow** [comment]
> 这台手机发起的

换个虚拟ip的网段试试呢。感觉是网段冲突了

**Comment by canronglan** [comment]
用安卓app的话，可以正常访问虚拟网段的，不是网段冲突，我现在有点怀疑iptables，下午测试一下iptables看看

**Comment by canronglan** [comment]
能用的那个note7是安卓10，这台手机是安卓13，不知道是不是安卓13的限制

**Comment by KKRainbow** [comment]
你这个手机ping其他手机也不通吗。可以试试 开着 tcpdump 的同时 ping 其他节点吗

**Comment by canronglan** [comment]
是的，双向都不通，试了同时ping和被ping都是没有任何数据包

**Comment by KKRainbow** [comment]
```
ip route add 192.168.124.0/24 dev easy0 proto kernel scope link src 192.168.124.30 table local
```

**Comment by Ffggjnf** [comment]
臥槽，我的正好相反，不開VPN 不能聯網，開VPN 才行。我用的ngrok
