### ISSUE TITLE
【BUG】GUI 不显示节点延迟、上传、下载、丢包率信息

### ISSUE THREAD

**Issue by SolomonLeon** [EasyTier/EasyTier#278]
如图所示：

<img width="579" alt="截图" src="https://github.com/user-attachments/assets/bbc36e72-32a3-49df-a2d8-a3aac07c0f56">

图中，`localhost` 是本地局域网内的手机，`vps` 是一台没有公网 IP 的云服务器。就算在 `vps` 上启动文件服务器并下载大文件，面板中仍然不显示节点延迟、上传、下载、丢包率信息。

**Comment by KKRainbow** [comment]
公共服务器转发是这样的，虽然显示 p2p 但是实际上还是走服务器转发的。

**Comment by KKRainbow** [comment]
这个 issue 可以保留一下，后面修了我再关

**Comment by SolomonLeon** [comment]
> 公共服务器转发是这样的，虽然显示 p2p 但是实际上还是走服务器转发的。

感谢回复！同时想请教一下，如果自己有一个公网服务器的话，可以搭建自己的转发节点吗？如果可以的话，请问如何搭建呢（没在文档中找到QAQ）

**Comment by KKRainbow** [comment]
readme 里有，官网我还没来得及更新
![QQ_1724556135117](https://github.com/user-attachments/assets/771e88a3-b1e0-4c5e-baea-3b00af89ab9b)

一般情况下你自用且只有一个虚拟网的话，让你的公网节点参与组网（相同的 network name / secret）就行
