### ISSUE TITLE
支持quic传输

### ISSUE THREAD

**Issue by Itsusinn** [EasyTier/EasyTier#284]
理论上应当可以显著提升性能https://github.com/libp2p/rust-libp2p/pull/3454
我希望做出贡献，不知道架构上可不可行？

**Comment by KKRainbow** [comment]
嗯嗯，实现了，但是没有默认编译进去，quic 体积有点大

**Comment by KKRainbow** [comment]
如果感兴趣，可以试试集成类似 udp2raw 的功能
