### ISSUE TITLE
添加多个服务器问题

### ISSUE THREAD

**Issue by xwshan** [EasyTier/EasyTier#285]
- 系统：win10
- 安装方式：Windows服务
- 软件版本：1.2.3
- 问题：延时居高不下

我发现 如果添加多个服务器地址  easytier不会选择效果最好的。可能是某个服务器原因，有的时候，导致延迟很高。
比如，除了添加了公共服务器之外，手动添加了一下其他人共享的服务器。
1. 在单独使用公共服务器的情况下，延时有100-140ms左右；
2. 在手动方式下添加多个服务器 (包括公共服务器) 时，延时高达500-800ms

多服务器的添加，不仅  不能改善使用体验，反而起到了反作用 😭 

😄 有没有考虑，使用多个服务器时，在保证easytier连通的前提下，自动完成测试，并选择连接速度最快的方式呢 😄 
仅供参考，越来越棒！

**Comment by shenjiangqiu** [comment]
有没有实施lantency-first模式?

**Comment by shenjiangqiu** [comment]
我在高级菜单里添加了这个选项,但是似乎原本默认的就是延迟优先, 所以可能也没有效果

**Comment by KKRainbow** [comment]
2.0 版本支持这种用法，欢迎试用
