### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by shenjiangqiu** [EasyTier/EasyTier#286]
rust version" 1.80.1",
macos aarch64
run : cargo install easytier

come up with:
error: the `cargo::` syntax for build script output instructions was added in Rust 1.77.0, but the minimum supported Rust version of `easytier v1.2.3 (/Users/xxx/Documents/git/EasyTier/easytier)` is 1.75.
Switch to the old `cargo:rerun-if-changed=proto/cli.proto` syntax (note the single colon).

**Comment by shenjiangqiu** [comment]
same problem for windows 11 x64

**Comment by KKRainbow** [comment]
would you like to submit a pr to change the 'rust-version' in easytier/Cargo.toml to '1.77'?
