### ISSUE TITLE
打洞功能在某些路由器上导致连接数激增，无法上网

### ISSUE THREAD

**Issue by 3RDNature** [EasyTier/EasyTier#289]
现象：
打开Easytier后，网络就寄了。过一会又好了，再过一会又寄了。怀疑是城中村垃圾网的问题，把网管心态搞崩了。
网络环境：NAT4

观察发现：
1. Easytier启动的时，会产生大量的UDP连接
![image](https://github.com/user-attachments/assets/50d8aa9b-7dd9-4293-bb36-8ea03c0b4cb8)
检查路由器后发现，造成的连接IP包括：
向其他位于nat4后方的节点公网IP造成的大量UDP链接、到路由器对应公网IP的UDP连接（疑似探测端口开放？）
结合日志分析，就是打洞行为无疑。
2. 在启动后，路由器会不定时的刷出报错：
```
Wed Aug 28 20:38:57 2024 kern.notice kernel: [171680.461669] nf_ct_snmp_trap: dropping packet: parser failed
Wed Aug 28 20:38:57 2024 kern.notice kernel: [171680.461669]  IN= OUT= SRC=172.16.100.2 DST=103.30.77.* LEN=52 TOS=0x00 PREC=0x00 TTL=127 ID=40309 PROTO=UDP SPT=58263 DPT=162 LEN=32
```

查询这条报错后得到一个有意思的issue: https://github.com/istoreos/istoreos/issues/1476 目前怀疑是路由器固件的坑。

是否可以通过 disable_p2p 来阻止这种打洞行为？ 目前没有尝试 因为GUI版没这个开关，也找不到配置文件的修改方式
https://github.com/EasyTier/EasyTier/issues/288

**Comment by bh1xaq** [comment]
同样遇到相同的问题，NTM 检测，EasyTier 的节点连接数 将近 5K 了

**Comment by zhufengme** [comment]
It looks very similar to my issue  #226

**Comment by 3RDNature** [comment]
已经clone代码，添加了一个disable_udp_hole_punch参数。明天睡醒了测

**Comment by 3RDNature** [comment]
> It looks very similar to my issue #226

yep, I can see more than 5~6k connection on my router so it shut my internet down. And packet length is 84. 
I can't just wait this bug fixed, because this bug shut my router down (in fact, it also shut my company's internet down). So I add a option to avoid NAT detection

**Comment by KKRainbow** [comment]
昨天看了下打洞逻辑有点问题，我尽快修复下
