### ISSUE TITLE
使用公网节点后如果udp打洞未成功，即使使用latency-first也会走公网节点转发

### ISSUE THREAD

**Issue by HmnSn** [EasyTier/EasyTier#293]
家里部署有三个节点（都在同一局域网里），在公司（无公网IP）进行连接，三个节点并不是每次都能同时打洞成功，像这样

![屏幕截图 2024-08-30 111059](https://github.com/user-attachments/assets/a2e6ecb8-0acf-48b8-9822-6d724be8f888)

没有DIRECT的节点走的是公网服务器转发，导致延迟和速度都不太理想，预期192.168.128.3节点next_hop_hostname应该走raspberrypi或者ImmortalWrt进行转发。
公司的节点开关latency-first表现相同，上图就是使用--latency-first时的截图，如果删除192.168.128.3节点启动参数里的-e tcp://easytier.public.kkrainbow.top:11010后，才会遵从上面的转发预期

**Comment by HmnSn** [comment]
新版本添加了显示版本和路由后，gui中未打洞成功走公共服务器转发的节点路由显示为本机，不知是否与该问题相关
<img width="1027" alt="屏幕截图 2024-09-14 094311" src="https://github.com/user-attachments/assets/416e842c-e0b6-4b31-b0ab-4fad50da43dc">

**Comment by KKRainbow** [comment]
这个是有 bug。。你可以用这个版本试试

https://github.com/EasyTier/EasyTier/actions/runs/10642914886

**Comment by KKRainbow** [comment]
@m1m1sha

**Comment by HmnSn** [comment]
> 这个是有 bug。。你可以用这个版本试试
> 
> https://github.com/EasyTier/EasyTier/actions/runs/10642914886
启动参数
`.\easytier-core.exe -i 192.168.128.4 -e tcp://easytier.public.kkrainbow.top:11010 --network-name **** --network-secret **** --no-listener --latency-first`
从ping延迟，next_hop_hostname和iperf3测速来看应该还是走的公共服务器转发
<img width="967" alt="屏幕截图 2024-09-14 102041" src="https://github.com/user-attachments/assets/f8f0dfe7-3756-4807-9250-c6d2fa88573e">

**Comment by m1m1sha** [comment]
我看了一下是 gui 判断是否是本机的条件的问题... 我修复一下

**Comment by KKRainbow** [comment]
> > 这个是有 bug。。你可以用这个版本试试
> > https://github.com/EasyTier/EasyTier/actions/runs/10642914886
> > 启动参数
> > `.\easytier-core.exe -i 192.168.128.4 -e tcp://easytier.public.kkrainbow.top:11010 --network-name **** --network-secret **** --no-listener --latency-first`
> > 从ping延迟，next_hop_hostname和iperf3测速来看应该还是走的公共服务器转发
> 
> <img alt="屏幕截图 2024-09-14 102041" width="967" src="https://private-user-images.githubusercontent.com/49606244/367480824-f8f0dfe7-3756-4807-9250-c6d2fa88573e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODMwNjgsIm5iZiI6MTcyNjI4Mjc2OCwicGF0aCI6Ii80OTYwNjI0NC8zNjc0ODA4MjQtZjhmMGRmZTctMzc1Ni00ODA3LTkyNTAtYzZkMmZhODg1NzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjVhNjkyMzU4MmQ3YzU2ZjdmNDE4YjA2NDA3YWZhYTNhY2NlNjZkNjZkZGU4ZDY4NDUxMjY0MTcxZmNlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fZodNrVP2QkkdnobR3trT41jD2FuR-_od7B482ymepc">

发一下 easytier-cli peer 的结果

**Comment by HmnSn** [comment]
> > > 这个是有 bug。。你可以用这个版本试试
> > > https://github.com/EasyTier/EasyTier/actions/runs/10642914886
> > > 启动参数
> > > `.\easytier-core.exe -i 192.168.128.4 -e tcp://easytier.public.kkrainbow.top:11010 --network-name **** --network-secret **** --no-listener --latency-first`
> > > 从ping延迟，next_hop_hostname和iperf3测速来看应该还是走的公共服务器转发
> > 
> > 
> > <img alt="屏幕截图 2024-09-14 102041" width="967" src="https://private-user-images.githubusercontent.com/49606244/367480824-f8f0dfe7-3756-4807-9250-c6d2fa88573e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODMwNjgsIm5iZiI6MTcyNjI4Mjc2OCwicGF0aCI6Ii80OTYwNjI0NC8zNjc0ODA4MjQtZjhmMGRmZTctMzc1Ni00ODA3LTkyNTAtYzZkMmZhODg1NzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjVhNjkyMzU4MmQ3YzU2ZjdmNDE4YjA2NDA3YWZhYTNhY2NlNjZkNjZkZGU4ZDY4NDUxMjY0MTcxZmNlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fZodNrVP2QkkdnobR3trT41jD2FuR-_od7B482ymepc">
> 
> 发一下 easytier-cli peer 的结果

<img width="966" alt="屏幕截图 2024-09-14 111543" src="https://github.com/user-attachments/assets/b538df7e-c521-472a-aaa4-ac5bff1a71aa">

**Comment by KKRainbow** [comment]
到 128.3 和 128.2 是确定 p2p 了。
你 iperf 和 ping 是针对哪个主机测的？

**Comment by HmnSn** [comment]
> 到 128.3 和 128.2 是确定 p2p 了。 你 iperf 和 ping 是针对哪个主机测的？

上一次时128.3不是直连，上上张图有ping128.1和128.3的对比，iper3当时测试的也是128.3

这是128.3 p2p和relay(2)时iper3测试结果对比
<img width="575" alt="屏幕截图 2024-09-14 114100" src="https://github.com/user-attachments/assets/1ac263f7-e2d2-4213-897f-df062bd5c8b6">
<img width="568" alt="屏幕截图 2024-09-14 114047" src="https://github.com/user-attachments/assets/edc8ee9b-f3cc-4e75-85c1-58e21a9620ba">
如果能128.3能通过128.1或128.2转发应该能达到p2p时相同的速度

**Comment by HmnSn** [comment]
2.0版本后问题已解决，能正确走低延迟路线而不是只从公共服务器转发
<img width="1236" alt="屏幕截图 2024-10-12 152745" src="https://github.com/user-attachments/assets/070cef22-0a3d-48ba-a706-7640e52284e2">
