### ISSUE TITLE
Address not available

### ISSUE THREAD

**Issue by lijingrs** [EasyTier/EasyTier#296]
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: AnyhowError(create rpc server failed. addr: 127.0.0.1:0, err: Address not available (os error 99))), location: Location { file: "easytier/src/easytier-core.rs", line: 668, col: 22 }, can_unwind: true, force_no_backtrace: false }

**Comment by KKRainbow** [comment]
这种一般是没初始化 loop 设备

**Comment by KKRainbow** [comment]
我优化了一下，rpc 也监听 0.0.0.0

**Comment by CHANTXU64** [comment]
我刚刚也遇到这个问题，因为我用的Arch Linux 的 Linux-hardened内核，没有启用tun模块，换了个内核就好了

```
panic occurred: PanicHookInfo { payload: Any { .. }, location: Location { file: ".cargo/registry/src/index.crates.io-6f17d22bba15001f/easytier-2.0.3/src/easytier-core.rs", line: 668, col: 22 }, can_unwind: true, force_no_backtrace: false }
```
