### ISSUE TITLE
增加客户端所有在线节点IP及版本显示功能

### ISSUE THREAD

**Issue by seocgr** [EasyTier/EasyTier#311]
1、不管是ui版本的节点，还是linux版本的在线peer说显示的节点一直是排除自身，这样我要添加新节点就要多一步看下本服务器的ip 防止新分配的IP与在用IP冲突。

2、之前群里提到过增加节点版本显示功能，使用到现在发现不同版本组网影响稳定性，如果可以显示版本号可以一目了然遗漏升级的节点。

**Comment by m1m1sha** [comment]
![image](https://github.com/user-attachments/assets/3494a825-6f99-4242-a219-19dd5c9d8698)
![image](https://github.com/user-attachments/assets/3f076d5c-93cd-49af-aa29-449370645b3b)
