### ISSUE TITLE
子网代理模式下，远程桌面卡住

### ISSUE THREAD

**Issue by es202517** [EasyTier/EasyTier#312]
两方都是openwrt，安装luci，ping一直跑着，远程连接子网远程桌面地址，切出来放一段时间再切回去，界面无反应，无法操作。
再连接回去，如果不是需要输入的界面就可以操作，如果是需要输入内容的界面就会又卡着（这条是我提这个issues发现的，我本来是打算在远程机访问git的）
本地op的ping结果
64 bytes from 192.168.2.1: seq=946 ttl=32 time=6.852 ms
64 bytes from 192.168.2.1: seq=947 ttl=32 time=6.445 ms
^C
--- 192.168.2.1 ping statistics ---
948 packets transmitted, 948 packets received, 0% packet loss
round-trip min/avg/max = 5.014/7.315/42.858 ms

远程机器的ping结果
64 bytes from 192.168.1.1: icmp_seq=978 ttl=64 time=0.493 ms
64 bytes from 192.168.1.1: icmp_seq=979 ttl=64 time=0.531 ms
64 bytes from 192.168.1.1: icmp_seq=980 ttl=64 time=0.506 ms
64 bytes from 192.168.1.1: icmp_seq=981 ttl=64 time=0.522 ms
64 bytes from 192.168.1.1: icmp_seq=982 ttl=64 time=0.548 ms
^C
--- 192.168.1.1 ping statistics ---
982 packets transmitted, 982 received, 0% packet loss, time 1004438ms
rtt min/avg/max/mdev = 0.282/0.540/0.811/0.053 ms

**Comment by lldacing** [comment]
我这边是几分钟左右就断了，使用原生远程桌面连接现象是卡主，使用xmanager连接断掉时会报一个错误
![image](https://github.com/user-attachments/assets/59a10924-ab1f-411e-bbfa-d1e8263cf41f)

测试组网（window B和openwrt在一个局域网，openwrt和windows A连接easytier公共服务器组网）：
![image](https://github.com/user-attachments/assets/48abf384-f276-41f3-91ae-a2339719eb96)

抓包显示openclashwrt请求A失败，然后A和B就断了
![image](https://github.com/user-attachments/assets/67a8ff17-7272-418b-975d-2749dbb92293)

wireshark完整报文
[子网代理-rdp-reset.zip](https://github.com/user-attachments/files/16917909/-rdp-reset.zip)

**Comment by cnjackchen** [comment]
我也是同样问题。
用虚拟IP好像没问题，用子网代理的IP就卡。

**Comment by es202517** [comment]
补充：moonlight+sunshine 串流游戏一样会出现这个问题

**Comment by cnjackchen** [comment]
我的两个网都有这个问题，一个是linux作为公共服务器 windows <-> linux <-> window，另一个是windows作为公共服务器 windows <-> windows <-> window，通过虚拟IP远程桌面正常，通过子网代理的IP远程桌面几分钟就卡死。

**Comment by KKRainbow** [comment]
有哪位好心人可以提供一下抓包结果：
1. RDP 客户端的
2. 做子网代理机器的

感激不尽

**Comment by KKRainbow** [comment]
udp 代理实现的有点问题，120s 后大概率会断开，很可能导致 rdp / moonlight 断连

**Comment by KKRainbow** [comment]
![QQ_1726066612149](https://github.com/user-attachments/assets/2b8be35a-5dc0-4725-837f-1baf780dbac5)

**Comment by KKRainbow** [comment]
easytier-core:
https://github.com/EasyTier/EasyTier/actions/runs/10814412423

easytier-gui:
https://github.com/EasyTier/EasyTier/actions/runs/10814412424

**Comment by cnjackchen** [comment]
谢谢大佬，坐等docker更新。
