### ISSUE TITLE
子网代理192.168.3.0/24无效

### ISSUE THREAD

**Issue by cnjackchen** [EasyTier/EasyTier#313]
本地网段192.168.0.0/24，本地电脑系统windows 10。

1) 远程内网A（10.13.x.x），easytier客户端所在系统windows 10 workstation，远程easytier设置子网代理后，从本地电脑访问10.13.x.x正常。

2) 远程内网B（192.168.3.x），easytier客户端所在系统windows 10，远程easytier设置子网代理（192.168.3.10或者192.168.3.0/24），从本地电脑可以ping通192.168.3.10，但是访问web服务（http://192.168.3.10）不通。

本地电脑显示路由表如附件。
![photo_6260531016154332867_y](https://github.com/user-attachments/assets/946e2ae5-7dcc-4304-8f72-702b2fdbe719)

**Comment by KKRainbow** [comment]
一般是防火墙问题，试试用命令行，加上 --use-smoltcp 参数

**Comment by cnjackchen** [comment]
果然是防火墙问题，远程内网电脑把EasyTier加入防火墙白名单就好了。
问题解决了，谢谢！
