### ISSUE TITLE
编译easytier-gui 报错

### ISSUE THREAD

**Issue by clywm520** [EasyTier/EasyTier#315]
Cannot find module 'tauri-plugin-vpnservice-api' or its corresponding type declarations.

**Comment by m1m1sha** [comment]
Could you provide more information? I'm not quite understanding why this error is occurring. The easytier-gui is using the tauri-plugin-vpnservice in its codebase.

**Comment by KKRainbow** [comment]
you should run `pnpm build` in `tauri-plugin-vpnservice-api` dir before build easytier-gui

**Comment by KKRainbow** [comment]
please ref to https://github.com/EasyTier/EasyTier/blob/main/.github/workflows/gui.yml

```
      - name: Install frontend dependencies
        run: |
          (cd easytier-gui; pnpm install)
          (cd tauri-plugin-vpnservice; pnpm install; pnpm build)
```
