### ISSUE TITLE
请问下使用ls-al和vim命令就卡死是什么原因呢

### ISSUE THREAD

**Issue by yangrz7** [EasyTier/EasyTier#328]

**Comment by KKRainbow** [comment]
信息不够，不知道

**Comment by KKRainbow** [comment]
完整的操作步骤

**Comment by shenjiangqiu** [comment]
这个我知道, 这个事wireguard的历史遗留bug,之前碰到过. 原因是tun设备设置的mtu太大了,导致最后udp的包太大,在一些网络环境下(比如带认真的wifi), 会导致udp直接丢包. 只要把mtu改小就可以.

**Comment by shenjiangqiu** [comment]
@KKRainbow 可以测试一下,很多人碰到过这个问题, ls  可以但是ls -la直接卡死, 因为ls -la传输量超过了一个包大小. 如果问题存在可以写到文档里.

**Comment by KKRainbow** [comment]
@shenjiangqiu 意思是用 wg 客户端连进来之后，wg 的 tun mtu 有问题么。et 的话会自动设置 mtu 的

**Comment by KKRainbow** [comment]
主要他啥也不说，根本没法判断

**Comment by shenjiangqiu** [comment]
应该不是wireguard的问题这里,我只是类比一下, 应该就是udp/tcp丢包的问题, 假如tun打包成1420的数据包, easytier可能最终加上一些元数据会打包成1480的包, 有些网络再加上一些元数据会超过1500,然后udp没法正确的拆分就丢包了.
@yangrz7 你可以试试吧mtu设小点看看问题是不是解决了,之前在wireguard issue里讨论过这个问题.

**Comment by yangrz7** [comment]
主要是这个环境现在没有了，我后面有环境再试试。感谢两位大佬😁
