### ISSUE TITLE
MacOS 安装失败

### ISSUE THREAD

**Issue by m2kar** [EasyTier/EasyTier#331]
错误截图：
<img width="260" alt="image" src="https://github.com/user-attachments/assets/f5e0926e-b6b1-4bdc-b329-f6815ee8674b">

版本：
 - easytier: v1.2.3
 - MacOS: 14.6.1 (23G93)
 - CPU: Apple M3 Pro

**Comment by KKRainbow** [comment]
<img width="788" alt="image" src="https://github.com/user-attachments/assets/3484c53d-e560-4e29-ab07-45f9e2614d5d">


https://www.easytier.top/guide/gui/
