### ISSUE TITLE
官方能提供make脚本么

### ISSUE THREAD

**Issue by clywm520** [EasyTier/EasyTier#334]
官方能提供make编译脚本么？或者是docker镜像编译容器.
我自已编译的 二进制文件，老是运行一段时间就闪退，用的master分支最新源码，或者提示 低版本Centos7运行时出现， version `GLIBC_2.29' not found。

**Comment by KKRainbow** [comment]
> 我自已编译的 二进制文件，老是运行一段时间就闪退
闪退的时候会生成一个 easytier-panic.log，可以发出来我看看原因。

centos 7 运行不了有两个解法
1. 在任意平台用 musl 编译： cargo build --target=x86_64-unknown-linux-musl
2. 在 centos7 上 cargo build，运行就不会有问题了

**Comment by KKRainbow** [comment]
编译命令可以参考
https://github.com/EasyTier/EasyTier/tree/main/.github/workflows

也可以在 actions 里找找，有最新的编译好的
