### ISSUE TITLE
[Bug/Feature Request] wg client can not connect to internet

### ISSUE THREAD

**Issue by tiennv-u2u** [EasyTier/EasyTier#344]
wg client is just connected to EasyTier network only and it can not reach the internet connection through VPN server(s)

## Steps to reproduce:

1. Execute on Node A 
```shell
easytier-core --ipv4 10.144.144.1 --vpn-portal wg://0.0.0.0:11013/10.14.14.0/24 --enable-exit-node --use-smoltcp
```

2. Execute on Node B:

```shell
easytier-core --ipv4 10.144.144.2 --peers udp://<Node A public ip>:11010  --proxy-networks 10.14.14.0/24 --exit-nodes 10.144.144.1 --use-smoltcp
```

3. Config wg client connected to access the EasyTier network
```
[Interface]
PrivateKey = <key>
Address = 10.14.14.0/32

[Peer]
PublicKey = <key>
AllowedIPs = 10.14.14.0/24, 10.144.144.0/24, 10.14.14.0/24
Endpoint = <Node A public ip>:11013
```

4. After client is connected here is the output log from Node A:
```
<ts>: vpn portal client connected. portal: wg://0.0.0.0:11013, client_addr: wg://<client public ip>:63792

connected_clients:
[
    "wg://<client public ip>:63792",
]
```

5. Use cmd `curl ifconfig.me`, the result was not return the VPN server’s public IP, instead it return my client’s IP.

### Details config:

| Config              | Node A | Node B |
| :-------- | :------: | :----: |
| ipv4        |   `10.144.144.1`   | `10.144.144.2` |
| peers     |     | `udp://<Node A public ip>:11010` |
| vpn-portal     | `wg://0.0.0.0:11013/10.14.14.0/24` |  |
|proxy-networks    |    | `10.14.14.0/24` |
| enable-exit-node |  `true`   | `false` |
| exit-nodes|     | `10.144.144.1` |
| disable-ipv6 |    |  |
| use-smoltcp |    |  |

## Expected:
- Client's ip address is changed to server's ip address.
- Traffic internet go out from client is exposed to VPN protocol as expected.

## Actual:
- Client's ip address **is not changed** to server's ip address.
- Traffic internet go out from client is set to default, there is no tunnel to EasyTier VPN servers  

## Environment:

- Node A, Node B server: Ubuntu
- wg client: wireguard app on iOS, MacOS

**Comment by KKRainbow** [comment]
swap 'enable exit node ' and ' enable exit node ' arg og node a and b

**Comment by tiennv-u2u** [comment]
@KKRainbow it still the same, my client can not reach the internet connection, here is the details cmd:

- Node A:
```
easytier-core --ipv4 10.144.144.1 --vpn-portal wg://0.0.0.0:11013/10.14.14.0/24 --exit-nodes 10.144.144.2 --disable-ipv6 --use-smoltcp
```

- Node B:
```
sudo easytier-core --ipv4 10.144.144.2 --peers udp://<Node A public ip>:11010  --proxy-networks 10.14.14.0/24 --enable-exit-node --use-smoltcp --disable-ipv6
```
