### ISSUE TITLE
[bug] 在wsl中启动报错

### ISSUE THREAD

**Issue by wms-why** [EasyTier/EasyTier#364]
### 描述问题 / Describe the bug

# 最新编译的easytier，在wsl中启动报错

1、
![image](https://github.com/user-attachments/assets/4922ca15-b814-4154-9b7e-d6e2f68d39a8)
2、
![image](https://github.com/user-attachments/assets/0f66fac6-206f-49f0-8baa-70150af1dbc7)

### 额外上下文 / Additional context

![image](https://github.com/user-attachments/assets/dd64d9f4-2d99-4759-9616-bbab1cb8b108)
![image](https://github.com/user-attachments/assets/ef4baa11-fcdf-4aa4-af99-cb4846c30308)

**Comment by KKRainbow** [comment]
可以试试从这里下载的启动会报错么
https://github.com/EasyTier/EasyTier/actions/runs/11007165965

另外 master 分支的代码跟旧版本 1.2.3 是不兼容的，不过也不应该发生 panic

**Comment by Hs-Yeah** [comment]
应该是权限问题，加上 sudo 试试？

**Comment by wms-why** [comment]
额， 看bash的前缀，我是以root启动的啊

**Comment by wms-why** [comment]
@KKRainbow 从这里下载的可以直接用，而且比较神奇的是，我再次运行我自己编译的，居然没问题了
