### ISSUE TITLE
[bug]  最新2.0版本（包括之前的）均有无法跑满上行带宽的情况

### ISSUE THREAD

**Issue by Ironboxplus** [EasyTier/EasyTier#382]
### 描述问题 / Describe the bug

1. 远程100M上行，本地200M下行，从远程传文件到本地（或者本地控制远程）
2. tailscale可以跑满，比如使用rustdesk远控，alist下载，均能达到12MB/S左右的速度
3. et只能跑到1-3MB/S左右，下载表现为速度不在上升，rustdesk表现为丢包和卡顿
4. 远程已经开启多线程，使用自建公网服务器，打洞成功，非中转（因为延迟很低）
5. 大概率可以排除单核瓶颈，因为局域网能跑到20M左右
6. 手机大概率触发，电脑小概率触发（大概）

### 重现步骤 / Reproduction

如上，进行任意高负载流量行为均可触发
![image](https://github.com/user-attachments/assets/3c6d66c5-35e2-492e-869e-cb434918dfe4)

### 预期结果 / Expected behavior

跑满12M

### 额外上下文 / Additional context

日志等会传，不过默认日志里除了
```
2024-09-26 16:29:59: connect to peer error. dst: tcp://xxx:11010, ip_version: V4, err: Err(Timeout(Elapsed(())))
2024-09-26 16:29:59: connect to peer error. dst: tcp://xxx:11010, ip_version: V4, err: Err(Timeout(Elapsed(())))
```
这种信息并没有其他的关于流控的log，晚上开debug日志看一下

**Comment by KKRainbow** [comment]
可以试试 2.0.3 版本，修复了一个 buffer 过小导致 tcp 带宽低的问题

**Comment by Ironboxplus** [comment]
> 可以试试 2.0.3 版本，修复了一个 buffer 过小导致 tcp 带宽低的问题

电脑的版本倒是没啥问题了，手机还是只有3M

**Comment by KKRainbow** [comment]
> > 可以试试 2.0.3 版本，修复了一个 buffer 过小导致 tcp 带宽低的问题
> 
> 电脑的版本倒是没啥问题了，手机还是只有3M

手机连 wifi 只有 3M 吗
