### ISSUE TITLE
[bug] 能看到组网数据但是ping不通

### ISSUE THREAD

**Issue by chenxudong2020** [EasyTier/EasyTier#386]
### 描述问题 / Describe the bug

服务器S上直接运行了 ./easytier-core 

由于涉及隐私 “服务器S的公网IP” 代替 实际是服务器S的公网IPV4 ！！！！！！！！！！！！！！！！！！
linux A 运行 ./easytier-core --ipv4 10.144.144.2 --network-name easytier --network-secret easytier -p udp://服务器S的公网IP:11010
window gui运行客户端配置
![image](https://github.com/user-attachments/assets/cc7a7dba-17c5-4d6d-a207-35d8059aa8ab)
刚开始是这样的如下图
![image](https://github.com/user-attachments/assets/1b8285f6-79ff-4904-a671-98ab8f2a28b9)
一段时间gui上显示unas变成p2p
但是window下却一直ping不通 10.114.114.2 如下图所示
![image](https://github.com/user-attachments/assets/b89d093f-c1b7-4fe3-9568-fef255034c4e)

已经检查了三台机器防火墙都是关闭的

### 重现步骤 / Reproduction

上面的配置

**Comment by KKRainbow** [comment]
虚拟ip要在同一个子网

**Comment by chenxudong2020** [comment]
麻烦告知哪里配置了 默认掩码？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月3日(周四) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [EasyTier/EasyTier] [bug] 能看到组网数据但是ping不通 (Issue #386)




 
虚拟ip要在同一个子网

**Comment by KKRainbow** [comment]
默认24子网

**Comment by chenxudong2020** [comment]
已经不指定了--ipv4 让其自动分配可以通了，  但是我想在服务端启动的时候指定分配的dhcp网址段 客户端启动全部配置 -d 怎么设置
