### ISSUE TITLE
[bug] 2.0.0版本很难p2p

### ISSUE THREAD

**Issue by jamebal** [EasyTier/EasyTier#396]
### 描述问题 / Describe the bug

1. 我有3台设备确认都是Full Cone Nat类型, 但是easytier显示为PortRestricted
2. 3台设备之间无法全部p2p
3. 使用tailscale,vnt等工具, 3台设备均可p2p直连
<img width="1037" alt="截屏2024-10-08 16 52 38" src="https://github.com/user-attachments/assets/3ca48a08-e234-4e4b-9389-d23f9295d132">
<img width="1054" alt="截屏2024-10-08 16 57 03" src="https://github.com/user-attachments/assets/be284792-5969-4a94-88fa-d87d30770592">

<img width="1042" alt="截屏2024-10-08 16 53 13" src="https://github.com/user-attachments/assets/865d18e7-4d2e-472e-8c08-1f67af459242">

### 预期结果 / Expected behavior

3台设备之间p2p打洞成功

**Comment by yeyun1999** [comment]
我也有一样的感觉，更新到2.0.1后，也没有改善

**Comment by KKRainbow** [comment]
> [yeyun1999](/yeyun1999)

怎么能联系到你，我需要看下你的环境

**Comment by yeyun1999** [comment]
> > [yeyun1999](/yeyun1999)
> 
> 怎么能联系到你，我需要看下你的环境

QQ 1799103922

**Comment by jamebal** [comment]
**现在2.0.0可以p2p, 但是2.0.1不行, 😂**

2.0.0多重启几次有时候可以p2p, 有时候不行, 感觉是看运气
2.0.1重启好多次都不行

<img width="1023" alt="截屏2024-10-09 09 25 39" src="https://github.com/user-attachments/assets/c582abf5-158e-49a6-b6de-5f2b6af5b07f">
<img width="1047" alt="截屏2024-10-09 09 35 58" src="https://github.com/user-attachments/assets/2cd73e3d-f191-4a28-9d23-db59455f8f2a">

**Comment by KKRainbow** [comment]
有个 nat3-nat3 打洞必定打不通的 bug，我尽快出新版

**Comment by jamebal** [comment]
> 有个 nat3-nat3 打洞必定打不通的 bug，我尽快出新版

我这个3台设备都是nat1

**Comment by KKRainbow** [comment]
> > 有个 nat3-nat3 打洞必定打不通的 bug，我尽快出新版
> 
> 我这个3台设备都是nat1

1跟3 一样的

**Comment by KKRainbow** [comment]
> 同样的问题，最近经常都是relay2，目前更新到了最新的版本2.0.2也没有改善

所有节点都升202也不能p2p吗

**Comment by TomIsFat** [comment]
> > 同样的问题，最近经常都是relay2，目前更新到了最新的版本2.0.2也没有改善
> 
> 所有节点都升202也不能p2p吗

不能，而且安卓端的还闪退，刚刚看闪退日志大概报的是IP错误

java.lang.IllegalArgumentException: Invalid IP addr string

**Comment by TomIsFat** [comment]
> > 同样的问题，最近经常都是relay2，目前更新到了最新的版本2.0.2也没有改善
> 
> 所有节点都升202也不能p2p吗

我刚刚才测试的，其他软件就可以，easytier总是无法p2p：
![image](https://github.com/user-attachments/assets/ab68f235-2807-457e-8067-6c32e313a013)
![image](https://github.com/user-attachments/assets/41a62338-1cd2-48ae-a87f-ce388c091689)

另外有没有方法可以让easytier只做直连，不中转

使用场景是看NAS下的视频

若我用皎月连，在恶劣环境下尝试十几次可能有一次成功p2p，视频可以加载，而easytier在这种环境下直接就relay2了，速度太慢以至于完全无法使用

**Comment by KKRainbow** [comment]
> > > 同样的问题，最近经常都是relay2，目前更新到了最新的版本2.0.2也没有改善
> > 
> > 
> > 所有节点都升202也不能p2p吗
> 
> 我刚刚才测试的，其他软件就可以，easytier总是无法p2p： ![image](https://private-user-images.githubusercontent.com/76768214/375963256-ab68f235-2807-457e-8067-6c32e313a013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDQ3NzAsIm5iZiI6MTcyODc0NDQ3MCwicGF0aCI6Ii83Njc2ODIxNC8zNzU5NjMyNTYtYWI2OGYyMzUtMjgwNy00NTdlLTgwNjctNmMzMmUzMTNhMDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDQ0YTRiZGYyMzA3NmE3NDhkZGY5ZWQxYmViM2JmNmNmYjllZDdlZjExNzc2MzhjMjg5NTYwODc4NjE0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lw3fSuh03pEh7oHDySoQa4T-tgpW87LtsoSADrIBUVo) ![image](https://private-user-images.githubusercontent.com/76768214/375963481-41a62338-1cd2-48ae-a87f-ce388c091689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDQ3NzAsIm5iZiI6MTcyODc0NDQ3MCwicGF0aCI6Ii83Njc2ODIxNC8zNzU5NjM0ODEtNDFhNjIzMzgtMWNkMi00OGFlLWE4N2YtY2UzODhjMDkxNjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MmEwYzdlYTExNWFiZjlmZWE5MDM5OTc5ZWY4OTZmOGM5NGY5YTFjMjNhNzU2MWZlZjdlZDcyY2ZhMDllOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qgXwBsL9qp6jc_axE5r0IDvvAceZaLXcZH_SC10t6A0)
> 
> 另外有没有方法可以让easytier只做直连，不中转
> 
> 使用场景是看NAS下的视频
> 
> 若我用皎月连，在恶劣环境下尝试十几次可能有一次成功p2p，视频可以加载，而easytier在这种环境下直接就relay2了，速度太慢以至于完全无法使用

麻烦提供一下你两个节点的 NAT 类型

**Comment by TomIsFat** [comment]
> > > > 同样的问题，最近经常都是relay2，目前更新到了最新的版本2.0.2也没有改善
> > > 
> > > 
> > > 所有节点都升202也不能p2p吗
> > 
> > 
> > 我刚刚才测试的，其他软件就可以，easytier总是无法p2p： ![image](https://private-user-images.githubusercontent.com/76768214/375963256-ab68f235-2807-457e-8067-6c32e313a013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDQ3NzAsIm5iZiI6MTcyODc0NDQ3MCwicGF0aCI6Ii83Njc2ODIxNC8zNzU5NjMyNTYtYWI2OGYyMzUtMjgwNy00NTdlLTgwNjctNmMzMmUzMTNhMDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDQ0YTRiZGYyMzA3NmE3NDhkZGY5ZWQxYmViM2JmNmNmYjllZDdlZjExNzc2MzhjMjg5NTYwODc4NjE0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lw3fSuh03pEh7oHDySoQa4T-tgpW87LtsoSADrIBUVo) ![image](https://private-user-images.githubusercontent.com/76768214/375963481-41a62338-1cd2-48ae-a87f-ce388c091689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDQ3NzAsIm5iZiI6MTcyODc0NDQ3MCwicGF0aCI6Ii83Njc2ODIxNC8zNzU5NjM0ODEtNDFhNjIzMzgtMWNkMi00OGFlLWE4N2YtY2UzODhjMDkxNjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MmEwYzdlYTExNWFiZjlmZWE5MDM5OTc5ZWY4OTZmOGM5NGY5YTFjMjNhNzU2MWZlZjdlZDcyY2ZhMDllOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qgXwBsL9qp6jc_axE5r0IDvvAceZaLXcZH_SC10t6A0)
> > 另外有没有方法可以让easytier只做直连，不中转
> > 使用场景是看NAS下的视频
> > 若我用皎月连，在恶劣环境下尝试十几次可能有一次成功p2p，视频可以加载，而easytier在这种环境下直接就relay2了，速度太慢以至于完全无法使用
> 
> 麻烦提供一下你两个节点的 NAT 类型

均为端口受限锥型NAT
![2024-10-12 23-05-00](https://github.com/user-attachments/assets/1e0c7a1b-9f50-4360-be0a-b554c6c21919)

**Comment by KKRainbow** [comment]
et测出来是什么类型

**Comment by TomIsFat** [comment]
> et测出来是什么类型

 Port Restricted

**Comment by KKRainbow** [comment]
> > et测出来是什么类型
> 
> Port Restricted


有遇到过 stun 测试返回错误 public ip 导致无法 p2p 的情况，我下个版本优化下

**Comment by HKMV** [comment]
> 2.0.3版本 p2p成功🎉, 而且很快, 基本10秒内就完成了

是的net3-net3现在很快
