### ISSUE TITLE
[bug] 2.0.1版本子网对子网ping不通，ssh链接没有问题

### ISSUE THREAD

**Issue by silingyuan0** [EasyTier/EasyTier#405]
### 描述问题 / Describe the bug

2.0.1版本子网对子网ping不通，ssh链接没有问题

**Comment by KKRainbow** [comment]
确实是有 bug，在未建立 p2p，而是使用服务器做中转时，子网代理的 udp 和 icmp 无法使用，tcp 不受影响

**Comment by hitoxiao** [comment]
已经建立了p2p还是会无法ping通，tcp端口正常访问
