### ISSUE TITLE
[bug] 2.0.2版本安卓APP运行网络后闪退

### ISSUE THREAD

**Issue by froclock** [EasyTier/EasyTier#408]
### 描述问题 / Describe the bug

2.0.2版本安卓端Easytier GUI运行网络后1~2s左右程序即闪退

### 重现步骤 / Reproduction

在使用2.0.2版本安卓端的Easytier GUI时，点击运行网络后1~2s左右程序即闪退，100%触发。完全无法使用Easytier。

### 预期结果 / Expected behavior

尽快修复这一Bug

### 额外上下文 / Additional context

无

**Comment by maoyusan** [comment]
+1，吾也碰到了

**Comment by maoyusan** [comment]
![Screenshot_2024-10-12-18-55-57-195_com miui third](https://github.com/user-attachments/assets/ad030a97-3b88-46b8-a9b3-1a88ff08d1e6)
帮你补个报错

**Comment by KKRainbow** [comment]
203 已修复
