### ISSUE TITLE
[bug] ubuntu运行报错

### ISSUE THREAD

**Issue by LionZzzi** [EasyTier/EasyTier#415]
### 描述问题 / Describe the bug

config.yaml文件如下

# 实例名称，用于在同一台机器上标识此 VPN 节点
instance_name = "aliyun-wlcb"
# 主机名，用于标识此设备的主机名
hostname = "home_server"
# 实例 ID，一般为 UUID，在同一个 VPN 网络中唯一
instance_id = "8ea389d5-bb2a-4918-8597-5a34827c0cb2"
# 此 VPN 节点的 IPv4 地址，如果为空，则此节点将仅转发数据包，不会创建 TUN 设备
ipv4 = "110.110.110.4"
# 由 Easytier 自动确定并设置IP地址，默认从10.0.0.1开始。警告：在使用 DHCP 时，如果网络中出现 IP 冲突，IP 将自动更改
dhcp = false

# 监听器列表，用于接受连接
listeners = [
"tcp://0.0.0.0:11010",
"udp://0.0.0.0:11010",
"wg://0.0.0.0:11011",
"ws://0.0.0.0:11011/",
"wss://0.0.0.0:11012/",
]

# 退出节点列表
exit_nodes = [
]

# 用于管理的 RPC 门户地址
rpc_portal = "0.0.0.0:15888"

[network_identity]
# 网络名称，用于标识 VPN 网络
network_name = "xxx"
# 网络密钥，用于验证此节点属于 VPN 网络
network_secret = "xxxxxxxx"

# 这里是对等连接节点配置，可以多段配置
[[peer]]
uri = "tcp://x.x.x.x:11010"

[flags]
# 连接到对等节点使用的默认协议
default_protocol = "tcp"
# TUN 设备名称，如果为空，则使用默认名称
dev_name = ""
# 是否启用加密
enable_encryption = true
# 是否启用 IPv6 支持
enable_ipv6 = true
# TUN 设备的 MTU
mtu = 1380
# 延迟优先模式，将尝试使用最低延迟路径转发流量，默认使用最短路径
latency_first = false
# 将本节点配置为退出节点
enable_exit_node = false
# 禁用 TUN 设备
no_tun = false
# 为子网代理启用 smoltcp 堆栈
use_smoltcp = false
# 仅转发白名单网络的流量，支持通配符字符串。多个网络名称间可以使用英文空格间隔。如果该参数为空，则禁用转发。默认允许所有网络。例如：'*'（所有网络），'def*'（以def为前缀的网络），'net1 net2'（只允许net1和net2）
foreign_network_whitelist = "*"

执行# 实例名称，用于在同一台机器上标识此 VPN 节点
instance_name = "aliyun-wlcb"
# 主机名，用于标识此设备的主机名
hostname = "home_server"
# 实例 ID，一般为 UUID，在同一个 VPN 网络中唯一
instance_id = "8ea389d5-bb2a-4918-8597-5a34827c0cb2"
# 此 VPN 节点的 IPv4 地址，如果为空，则此节点将仅转发数据包，不会创建 TUN 设备
ipv4 = "110.110.110.4"
# 由 Easytier 自动确定并设置IP地址，默认从10.0.0.1开始。警告：在使用 DHCP 时，如果网络中出现 IP 冲突，IP 将自动更改
dhcp = false

执行./easytier-core -c config.yaml 报错

panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: AnyhowError(failed to add listener tcp://0.0.0.0:11010

Caused by:
    0: io error
    1: Address in use (os error 98))), location: Location { file: "easytier/src/easytier-core.rs", line: 667, col: 22 }, can_unwind: true, force_no_backtrace: false }

**Comment by zdwtest** [comment]
listeners里面这个"ws://0.0.0.0:11011/"参数会不会不太对，可能不能加"/"？🤔️

**Comment by zdwtest** [comment]
1: Address in use (os error 98))), location: Location { file: "easytier/src/easytier-core.rs", line: 667, col: 22 }, can_unwind: true, force_no_backtrace: false }

不过这个报错应该是端口占用了，你查查11010端口也没有占用

**Comment by zdwtest** [comment]
是不是用了一键脚本安装的
