### ISSUE TITLE
[feat] 增加编译说明

### ISSUE THREAD

**Issue by rekey** [EasyTier/EasyTier#428]
### 描述问题 / Describe the problem

默认release没有quic支持，这试图自己编译带quic支持，在另一台机器上运行提示 

./easytier-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./easytier-core)
./easytier-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./easytier-core)
./easytier-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./easytier-core)

### 描述您想要的解决方案 / Describe the solution you'd like

默认编译带quic的版本，或者给一个说明文档方便自己编译

我这边编译环境debian12

**Comment by KKRainbow** [comment]
试试用低版本的发行版编译，或者编译 musl 版本，具体可以参考 .github 目录下的 ci 脚本

**Comment by rekey** [comment]
按照作者说的琢磨了一个编译简单步骤，提供给大家。

https://xifa.fun/2024/11/01/debian12_build_easytier/
