### ISSUE TITLE
[bug] gui客户端out of memory

### ISSUE THREAD

**Issue by FuturePrayer** [EasyTier/EasyTier#430]
### 描述问题 / Describe the bug

![image](https://github.com/user-attachments/assets/4f3417bf-72a4-44b4-8bff-cd0012519cb5)

### 重现步骤 / Reproduction

启动一个GUI客户端，连上网络后挂在后台，一段时间后再回来看，就会出现如图所示提示

### 预期结果 / Expected behavior

修复内存泄漏问题

**Comment by FuturePrayer** [comment]
另外一台设备还出现了内存占用高的问题
![79ca5aaf6de1852895cb27f2f82a1dea](https://github.com/user-attachments/assets/99cc9eb5-4688-4aec-a0cc-cbd70b7168b6)

**Comment by KKRainbow** [comment]
怀疑是 vue 的 bug
https://github.com/vuejs/core/issues/12181

**Comment by ifnk** [comment]
我这也有这个问题，内存占用高达 2.9 G ,环境是 win11 i9 64G  ，另一个用tauri 写的 clash verge  写的 一直显示页面  ，跑了一天也就 8.9m 内存占用

**Comment by kevin335200** [comment]
2.2.4 版本仍然碰到，时间挂了一两天左右就会出现：

![Image](https://github.com/user-attachments/assets/2dc167ff-6c4a-4a9f-8ddb-34a5ef9e6c64)

**Comment by jingouwangzi** [comment]
我也是，偶尔界面崩溃，内存占用有时会上3-4G

**Comment by KKRainbow** [comment]
224 的泄漏修了，还没发布
