### ISSUE TITLE
出口节点是不是配置无效呢

### ISSUE THREAD

**Issue by clywm520** [EasyTier/EasyTier#432]
### 描述问题 / Describe the bug

服务器A有公网IP 命令行启动如下 ./easytier-core --enable-exit-node    --ipv4 192.168.124.1  
另一台服务器B连接A   ./easytier-core --ipv4 192.168.124.2 --exit-nodes 192.168.124.1  --peers  udp://A服务器公网IP:11010 

在B服务器查看此时的公网IP，还是原来的IP，并不显示A的公网IP。是配置有问题吗？

**Comment by clywm520** [comment]
版本都  2.0.3

**Comment by KKRainbow** [comment]
需要手动配置一下B的默认路由

**Comment by clywm520** [comment]
可以示例一下相关的命令么。

**Comment by KKRainbow** [comment]
这个命令不敢随便给，改坏了容易上不了网，大概思路是让把 et 的 tun 设备设置为默认路由的出口设备

**Comment by jimmyshengle** [comment]
安卓手机怎么搞

**Comment by otkmaster** [comment]
电脑都好弄，安卓咋处理

**Comment by totti2202344** [comment]
这个举个例子看看怎么写2.4.2这个好像还是不行哦

**Comment by gdtv** [comment]
> 这个举个例子看看怎么写2.4.2这个好像还是不行哦

我已经放弃了，改用tailscale了
