### ISSUE TITLE
[feat] 希望可以跟代理软件共存

### ISSUE THREAD

**Issue by cheng1nuo** [EasyTier/EasyTier#434]
### 描述问题 / Describe the problem

windows 上可以使用CLI版本 使用socks5+--no-tun来细致化分流
Android 只有GUI版本不能打开socks5监听和 --no-tun

### 描述您想要的解决方案 / Describe the solution you'd like

希望GUI版本可以打开socks5监听和--no-tun

### 替代方案 / Alternatives considered

或者为Android平台提供cli版本

**Comment by KKRainbow** [comment]
android 可以用 termux 执行对应架构的 linux 二进制。在 root 之后可以支持跟其他 vpn 同时使用

gui 版本受限于安卓系统限制没法实现你的需求，你可以试试在 qq 群里咨询下怎么搞，有人是这么用的但是我不太会

**Comment by cheng1nuo** [comment]
![Screenshot_2024-10-19-14-11-29-167_tornaco apps shortx](https://github.com/user-attachments/assets/615d31bb-641f-4d5a-aaf8-959230951042)
感谢您的提醒 linux-aarch64 确实可以在root权限下正常运行 我通过ShortX+实现了自动化启停 Easytier
