### ISSUE TITLE
[bug] 在桌面上运行GUI客户端，长时间运行后会导致webview2占用大量内存。

### ISSUE THREAD

**Issue by xiaony3527** [EasyTier/EasyTier#441]
### 描述问题 / Describe the bug

我后台挂客户端大概4天左右，WebView2管理器在任务管理器中显示占用了超过5g的内存。
![微信截图_20241022162429](https://github.com/user-attachments/assets/946ce98e-8f0f-4467-ac3c-18795e773082)

**Comment by xiaony3527** [comment]
![image](https://github.com/user-attachments/assets/48194e57-4ebf-4950-b67e-1948e58c4be3)
这次是运行了两天

**Comment by m1m1sha** [comment]
应该还是前端依赖vue的问题，尝试回退之后的版本 [action](https://github.com/EasyTier/EasyTier/actions/runs/11453775622) 呢，我本地测试都没有再发现这个问题

**Comment by ZhaoZelin2000** [comment]
![image](https://github.com/user-attachments/assets/78eb17a3-fb38-41af-be6a-6201e4b0d018)
我也遇见这个问题了，希望能在下个版本修复

**Comment by KKRainbow** [comment]
https://github.com/EasyTier/EasyTier/actions/runs/11765982925
可以试试这里的版本

**Comment by ZhaoZelin2000** [comment]
此版本不能正常运行，提示如下，且不能删除当前网络
invalid args `cfg` for command `parse_network_config`: invalid type: string "PublicServer", expected i32
![image](https://github.com/user-attachments/assets/1d918c74-f075-479a-b937-c1b158c9852e)


> https://github.com/EasyTier/EasyTier/actions/runs/11765982925 可以试试这里的版本

**Comment by ZhaoZelin2000** [comment]
此版本不能正常运行，提示如下，且无法删除网络
invalid args `cfg` for command `parse_network_config`: invalid type: string "PublicServer", expected i32

![image](https://github.com/user-attachments/assets/7f14bfbb-5a24-4c59-a9e2-c2f5c149a5ae)


> https://github.com/EasyTier/EasyTier/actions/runs/11765982925 可以试试这里的版本

**Comment by KKRainbow** [comment]
应该是 fix 了，问题关了

**Comment by hsj1992** [comment]
现在使用的是v2.0.3的easytier GUI,目前运行两三天的占用内存如图。这是正常占用嘛？
![20241221-121053](https://github.com/user-attachments/assets/1554bb3d-52e2-48b7-8650-0015f12ad83f)
