### ISSUE TITLE
增加备选服务器选项，如果首选服务器无法连接，自动切换至备选服务器

### ISSUE THREAD

**Issue by Gabriel-six** [EasyTier/EasyTier#447]
### 描述问题 / Describe the problem

个人目前将easytier服务用于nas，若服务器无法连接，我将不能在外接入nas，也无法接入后台手动切换easytier的服务器地址以恢复连接。所以期望加入服务器备选项，以用于首选项不能联通时候的自动切换。

### 描述您想要的解决方案 / Describe the solution you'd like

增加一到两个备选服务器选项，如果首选服务器无法连接，自动切换至备选服务器，或者说在手动指定的服务器无法联通时自动切换至官方的公共服务器。

**Comment by KKRainbow** [comment]
-p 指定多个就行

**Comment by Gabriel-six** [comment]
> Member

好的，谢谢您。另外在GUI界面目前好像还不能设置多个是吗

**Comment by KKRainbow** [comment]
可以用手动模式
