### ISSUE TITLE
[bug] linux安装gui之后，如何启动

### ISSUE THREAD

**Issue by yz-qc** [EasyTier/EasyTier#464]
### 描述问题 / Describe the bug

![image](https://github.com/user-attachments/assets/36f6768f-699f-46a8-97fa-646f55e1426b)
linux安装gui之后，如何启动，我想要从网页进入gui界面编辑

**Comment by KKRainbow** [comment]
linux gui 不是网页，需要桌面环境运行

**Comment by yz-qc** [comment]
> 

好吧，我以为有网页端的gui环境，感觉这样会比较好一点，谢谢，了解了

**Comment by KKRainbow** [comment]
嗯，下个版本会有
