### ISSUE TITLE
[feat] 能否提供一个选项，让节点通过特定的节点进行 relay 而不使用 p2p

### ISSUE THREAD

**Issue by yaonan** [EasyTier/EasyTier#475]
### 描述问题 / Describe the problem

请问是否可以提供一个配置项，让节点与其他节点之间只通过指定的节点（公共服务器）进行 relay，不使用 p2p。

主要是两个节点之间虽然可以成功 p2p，但网络不够稳定，想要可以指定强制使用公有云上部署的公共服务器进行中转。

### 描述您想要的解决方案 / Describe the solution you'd like

希望可以像 n2n 的 `-S1` `-S2` 参数一样，有个类似 [[relay]] 配置项，指定一组 peer 作为 relay server

**Comment by lightfirst** [comment]
禁用P2P不就行了

**Comment by yaonan** [comment]
> 禁用P2P不就行了

感谢提醒，在官网文档中没有看到这个配置，看了下源码找到了 `disable_p2p`
