### ISSUE TITLE
[bug] 每隔一段时间就报错11010 io异常然后服务就停止了， 这是什么原因？怎么规避一下？

### ISSUE THREAD

**Issue by wokul** [EasyTier/EasyTier#483]
### 描述问题 / Describe the bug

错误日志

easytier-core[28947]: 2024-11-20 03:55:21: listener accept failed. listener: tcp://0.0.0.0:11010, msg: io error
Nov 20 05:36:34 iz2zearvsmungntpgbcum3z easytier-core[28947]: panic occurred: PanicInfo { payload: Any { .. }, message: Some(standalone server listener exit), location: Location { file: "easytier/src/proto/rpc_impl/standalone.rs", line: 113, col: 13 }, can_unwind: true, force_no_backtrace: false }
Nov 20 05:36:34 iz2zearvsmungntpgbcum3z systemd[1]: easytier.service: main process exited, code=exited, status=1/FAILURE

**Comment by KKRainbow** [comment]
怎么复现

**Comment by KKRainbow** [comment]
如果有可能最好能把你的机器借我登录下

**Comment by wokul** [comment]
> 怎么复现

```
[Unit]
Description = easytier server
After = network.target syslog.target
Wants = network.target

[Service]
Type = simple
ExecStart = /usr/bin/easytier-core --network-name xxxx --network-secret xxx --relay-network-whitelist --relay-all-peer-rpc

[Install]
WantedBy = multi-user.target
```

正常`systemctl start easytier`启动 之前一直没问题 最近两周有过报这个错误 然后服务就停止了

**Comment by wokul** [comment]
> 如果有可能最好能把你的机器借我登录下

![image](https://github.com/user-attachments/assets/4a7363fb-b0d3-4321-b41e-30a9afe72750)
对我暂时问题不大 提供机器有点麻烦了 哈哈
