### ISSUE TITLE
[question] 关于退出节点转发流量的逻辑问题

### ISSUE THREAD

**Issue by bh1xaq** [EasyTier/EasyTier#495]
### 描述问题 / Describe the question

服务器 B 作为服务器 A 的退出节点，我从服务器 A ping -I et 网卡 114.114.114.114

我在服务器 B（退出节点）上 tcpdmp 抓 icmp 包，如果指定 et 网卡，则抓不到任何包。如果抓 any 网卡，则可以抓到来自物理网卡，目的为 114.114.114.114 的包。

### 重现步骤 / Reproduction

服务器 B 作为服务器 A 的退出节点，我从服务器 A ping -I et 网卡 114.114.114.114

我在服务器 B（退出节点）上 tcpdmp 抓 icmp 包，如果指定 et 网卡，则抓不到任何包。如果抓 any 网卡，则可以抓到来自物理网卡，目的为 114.114.114.114 的包。

### 预期结果 / Expected behavior

想问一下这个流量应该是怎么走的。为啥在 et 网卡上抓不到包？

### 额外上下文 / Additional context

暂无

**Comment by KKRainbow** [comment]
作为出口节点时，et如果发现收到的包是ping包，会直接构造一个icmp包发到目的端并等待响应，不会过虚拟网卡

**Comment by bh1xaq** [comment]
了解了，我使用tcp包尝试，确实可以抓到tun网卡的包，icmp不会。感谢回复。
