### ISSUE TITLE
[bug] 使用2.0.3版本时无法与其他的2.0.3版本用户打洞，全部都是relay（2）

### ISSUE THREAD

**Issue by SiebreAZ** [EasyTier/EasyTier#502]
### 描述问题 / Describe the bug

首先感谢软件的开发者！
我是受朋友推荐来尝试easytier软件的，本人对电脑编程之类的不很了解，所以如果有什么我忽略了的地方请麻烦知会我，抱歉+谢谢！！

以下是我遇到的问题：
只能够连接到server但是无法和同server下的其他用户打洞，一直显示relay（2）. 
p.s. 已经确认了把easytier添加到windows defender和firewall的白名单

这是easytier界面的截图：
![image](https://github.com/user-attachments/assets/524ba28c-bbf3-46d8-937d-e9feb5662cf1)

这是event log：
1 minute ago
ListenerAdded
ring://db83e739-5965-496b-be2a-ed392169a2b3
1 minute ago
ListenerAdded
tcp://0.0.0.0:11010
1 minute ago
ListenerAdded
udp://0.0.0.0:11010
1 minute ago
ListenerAdded
wg://0.0.0.0:11011
1 minute ago
ListenerAdded
udp://[::]:49177
1 minute ago
TunDeviceReady
et_9_ifgv
1 minute ago
Connecting
tcp://public.easytier.top:11010
1 minute ago
PeerConnAdded
{
  "conn_id": "7cb5e69f-b1a4-4990-94d7-402632df4715",
  "features": [],
  "is_client": true,
  "loss_rate": 0,
  "my_peer_id": 2756537839,
  "network_name": "easytier",
  "peer_id": 3345662835,
  "stats": {
    "latency_us": 0,
    "rx_bytes": 78,
    "rx_packets": 1,
    "tx_bytes": 93,
    "tx_packets": 1
  },
  "tunnel": {
    "local_addr": {
      "url": "tcp://10.88.111.4:3325"
    },
    "remote_addr": {
      "url": "tcp://public.easytier.top:11010"
    },
    "tunnel_type": "tcp"
  }
}
1 minute ago
PeerAdded
3345662835

**Comment by KKRainbow** [comment]
你这个机器是有白名单吗。

**Comment by KKRainbow** [comment]
某个地方没有放行监听端口 11010 ，检查一下
