### ISSUE TITLE
[bug] error: failed to run custom build command for `easytier v2.0.3`

### ISSUE THREAD

**Issue by ActivePeter** [EasyTier/EasyTier#503]
### 描述问题 / Describe the bug

error: failed to run custom build command for `easytier v2.0.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installThbyON/release/build/easytier-f18e0a406b57d0d0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/proto/peer_rpc.proto
  cargo:rerun-if-changed=src/proto/common.proto
  cargo:rerun-if-changed=src/proto/error.proto
  cargo:rerun-if-changed=src/proto/tests.proto
  cargo:rerun-if-changed=src/proto/cli.proto

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/easytier-2.0.3/build.rs:151:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: peer_rpc.proto:13:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\npeer_rpc.proto:15:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\npeer_rpc.proto:76:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\npeer_rpc.proto:191:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `easytier v2.0.3`, intermediate artifacts can be found at `/tmp/cargo-installThbyON`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

### 重现步骤 / Reproduction

在linux上执行 cargo install easytier

### 预期结果 / Expected behavior

安装成功

### 额外上下文 / Additional context

root@lab4:~# rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)

**Comment by KKRainbow** [comment]
你装的 protobuf compiler 版本跟 et 使用的不兼容
