### ISSUE TITLE
[bug] 连接手机热点后p2p打洞失败，连wifi时正常，2.0.3版本

### ISSUE THREAD

**Issue by langsisi** [EasyTier/EasyTier#505]
### 描述问题 / Describe the bug

使用wifi时p2p正常
<img width="601" alt="wifi" src="https://github.com/user-attachments/assets/b7a486b9-44cf-4e4d-b3c1-93daed45691f">
使用热点时p2p失败
![热点](https://github.com/user-attachments/assets/79e99c26-67ec-4eac-8250-6efc22e0f520)
只是切换手机热点，没有动其他地方，不知道是什么原因导致的，如何排查

**Comment by AndreyYukavichin** [comment]
因为你家里的宽带是NAT3类型（如图port restricted），所以wifi容易打洞。而手机热点是运营商的NAT4类型（如图Symmetric），所以打洞不成功。
