### ISSUE TITLE
[bug] 公共服务器连不上了吗？

### ISSUE THREAD

**Issue by kecikeci** [EasyTier/EasyTier#507]
### 描述问题 / Describe the bug

[bug] 公共服务器连不上了吗？

![image](https://github.com/user-attachments/assets/aeb07692-c8dd-453a-9722-46aa1e012d30)

**Comment by KKRainbow** [comment]
这个是你 dns 的问题吧？

**Comment by kecikeci** [comment]
> 这个是你 dns 的问题吧？

还真是，无语
