### ISSUE TITLE
[bug] 最近经常出现panic occurred

### ISSUE THREAD

**Issue by LionZzzi** [EasyTier/EasyTier#509]
### 描述问题 / Describe the bug

机器: MacBook M1 pro
easytier版本: 2.0.3
命令: sudo ./easytier-core --network-name xxx --network-secret xxx --ipv4 110.110.110.2 --peers tcp://xxx:11010 --hostname macbook --no-listener
之前用gui老是动不动就闪退, 我还一度以为是有bug.换成命令行启动运行一段时间就出现
panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Option::unwrap()` on a `None` value), location: Location { file: "easytier/src/connector/udp_hole_punch/sym_to_cone.rs", line: 327, col: 63 }, can_unwind: true, force_no_backtrace: false }

**Comment by KKRainbow** [comment]
确实，这里有问题，我修一下

**Comment by Angel0726** [comment]
> 确实，这里有问题，我修一下

我用的armbian系统，也报这个错误

**Comment by kettly1260** [comment]
ubuntu同样存在这个问题
panic occurred: PanicInfo { payload: Any { .. }, message: Some(standalone server listener exit), location: Location { file: "easytier/src/proto/rpc_impl/standalone.rs", line: 113, col: 13 }, can_unwind: true, force_no_backtrace: false }

**Comment by KKRainbow** [comment]
> ubuntu同样存在这个问题 panic occurred: PanicInfo { payload: Any { .. }, message: Some(standalone server listener exit), location: Location { file: "easytier/src/proto/rpc_impl/standalone.rs", line: 113, col: 13 }, can_unwind: true, force_no_backtrace: false }

你这个问题不一样，单独提一个吧

**Comment by KKRainbow** [comment]
> ### 描述问题 / Describe the bug
> 机器: MacBook M1 pro easytier版本: 2.0.3 命令: sudo ./easytier-core --network-name xxx --network-secret xxx --ipv4 110.110.110.2 --peers tcp://xxx:11010 --hostname macbook --no-listener 之前用gui老是动不动就闪退, 我还一度以为是有bug.换成命令行启动运行一段时间就出现 panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Option::unwrap()` on a `None` value), location: Location { file: "easytier/src/connector/udp_hole_punch/sym_to_cone.rs", line: 327, col: 63 }, can_unwind: true, force_no_backtrace: false }
> 
> ### 重现步骤 / Reproduction
> _No response_
> 
> ### 预期结果 / Expected behavior
> _No response_
> 
> ### 额外上下文 / Additional context
> _No response_

210 版本已修复
