### ISSUE TITLE
panic occurred: PanicInfo 错误

### ISSUE THREAD

**Issue by Angel0726** [EasyTier/EasyTier#512]
### 描述问题 / Describe the bug

panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: AnyhowError(failed to add listener tcp://0.0.0.0:11010

Caused by:
    0: io error
    1: Address in use (os error 98))), location: Location { file: "easytier/src/easytier-core.rs", line: 668, col: 22 }, can_unwind: true, force_no_backtrace: false }

### 重现步骤 / Reproduction

运行easytier-core --ipv4   ****   了--peers  ***  出现问题

**Comment by KKRainbow** [comment]
根据你提供的错误信息，程序在尝试添加监听器（listener）到 `tcp://0.0.0.0:11010` 时发生了恐慌（panic）。具体来说，这个错误发生在 `easytier/src/easytier-core.rs` 文件的第668行。错误的根本原因是操作系统级别的错误：地址已经被使用（Address in use, os error 98）。

这种错误通常意味着端口 `11010` 当前已经被另一个进程占用。这里有一些解决这个问题的方法：

1. **查找并停止占用端口的进程**：
   - 你可以使用命令如 `netstat`, `lsof`, 或者 `ss` 来找出哪个进程正在使用该端口。
   - 在Linux或macOS上，你可以运行类似以下命令来查找占用端口的进程：
     ```
     lsof -i :11010
     ```
     或者
     ```
     sudo netstat -tulnp | grep :11010
     ```
   - 找到进程ID (PID) 后，可以使用 `kill` 命令终止它：
     ```
     kill -9 <PID>
     ```

2. **更改你的应用程序监听的端口**：
   - 如果可能的话，修改你的应用配置，使其监听一个不同的、未被使用的端口。

3. **等待一段时间再试**：
   - 如果这是由于最近刚刚关闭了一个使用相同端口的应用程序，有时候需要等一会儿，因为端口可能会处于TIME_WAIT状态一段时间。

4. **检查防火墙设置**：
   - 确保防火墙或其他网络配置没有以某种方式阻止端口的使用。

5. **重启系统**：
   - 如果上述方法都无效，最后的选择是重启计算机，这将释放所有被占用的端口。

请根据实际情况选择合适的方法解决问题。如果你没有权限或者不确定如何操作，请联系系统的管理员寻求帮助。
