### ISSUE TITLE
[bug] 启动报错

### ISSUE THREAD

**Issue by JeffreyLiuJunJie** [EasyTier/EasyTier#513]
### 描述问题 / Describe the bug

panic occurred: PanicInfo { payload: Any {
..  }, message: Some(called `Result::unwrap()` on an `Err` value: TunError(Io(Os { code:
2, kind: NotFound, message: "No such file or directory" }))), location: Location { file
: "easytier/src/easytier-core. rs", line: 668, col: 22 }, can_unwind: true, force_no_back
trace: false }
Dec 14 18:06:24 Box systemd[1]: easytier. service: Main proc
ess exited, code=exited, status=1/FAILURE
Dec 14 18:06:24 Box systemd[1]: easytier.servic
e: Failed with result 'exit-code'

**Comment by PeggyPro** [comment]
描述不清
