### ISSUE TITLE
[bug] 使用easytier后vscode插件更新出问题

### ISSUE THREAD

**Issue by ydlqsb** [EasyTier/EasyTier#520]
### 描述问题 / Describe the bug

我在3台电脑，一个是debian12安装在虚拟机中，其他2台是win11系统台机。使用easytier组网后，vscode插件更新就一直提示正在安装，直到超时报错。困扰我有一个月，今天使用一台未使用easytier的笔记本在同一网络路由下就可以顺利更新插件。不知道有没人遇到相同情况。

**Comment by KKRainbow** [comment]
你的 et 配置是什么。是不是跟你梯子冲突了

**Comment by ydlqsb** [comment]
> 你的 et 配置是什么。是不是跟你梯子冲突了
在有公网ip的机器上建了个服务器，注册了个动态域名
其他windows机器用的gui程序，debian虚拟机照着文档安装成了systemd服务
按自己设置修改了" ExecStart=/root/easytier-core --ipv4 x.x.x.x --network-name xxx --network-secret xxx --peers tcp://xxx.xxx.xxx:11010" 带x的内容  
debian虚拟机没装梯子，只是改了hosts文件，添加了github网站的一些ip
有空我把那台没问题的笔记本也安装一下gui程序，看看使用后会不会也更新不了插件，再确认一下是不是和使用easytier有关

**Comment by ydlqsb** [comment]
刚才把debian虚拟机和一台windows机器 vscode插件全部清空后，重新安装插件恢复正常了，我的vscode用的同一个账号登陆打开了设置同步，估计有那个插件有bug或是冲突。

**Comment by ydlqsb** [comment]
手动清空插件目录后重装插件恢复正常了，我的vscode打开了设置同步，估计有那个插件有问题被同步了，所以3台机器同时出了问题，又凑巧电信把我的公网IP封了 ，就使用了easytier组网，这些刚好赶在一起让我误以为是easytier组网造成的，不好意思浪费你们的时间。
________________________________
发件人: Sijie.Sun ***@***.***>
发送时间: 2024年12月20日 16:15
收件人: EasyTier/EasyTier ***@***.***>
抄送: ydlqsb ***@***.***>; Author ***@***.***>
主题: Re: [EasyTier/EasyTier] [bug] 使用easytier后vscode插件更新出问题 (Issue #520)


其他节点有开子网代理么，是不是传播的路由跟你的梯子有冲突

―
