### ISSUE TITLE
[bug] 关于安卓应用在后台运行再次点进应用后闪退的BUG

### ISSUE THREAD

**Issue by LazyCat2333** [EasyTier/EasyTier#527]
### 描述问题 / Describe the bug

在软件还在后台运行的情况下，划掉后台卡片，并再次打开软件会出现闪退的BUG。

软件版本：V2.0.8
安卓版本：14
设备：三星

### 重现步骤 / Reproduction

在系统设置里允许应用在后台运行，点进应用进行连接组网，之后再退出应用，并把后台卡片划掉，这时候应用还是会在后台运行的（此时VPN还连着，说明应用还在后台运行），这时候再次点击进入app就会闪退了。系统显示应用“濒临崩溃”，之前还连着的vpn也断掉了。

重现视频：https://6jw6qp-my.sharepoint.com/:v:/g/personal/lazycat_6jw6qp_onmicrosoft_com/Efr9vwzNuaVMoU5CR8FJBfoBqzRsnxrzguIQH2R0T9F4EA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=SqKjkx
![Screenshot_20241222_003102_Smart Manager](https://github.com/user-attachments/assets/742bff2c-21d1-44d7-99fa-285854bc7a60)

**Comment by KKRainbow** [comment]
猜测与 wry 的这个提交有关系
https://github.com/tauri-apps/wry/pull/1414
