### ISSUE TITLE
[bug] 用着用着就自己停止运行了

### ISSUE THREAD

**Issue by kettly1260** [EasyTier/EasyTier#532]
### 描述问题 / Describe the bug

panic occurred: PanicInfo { payload: Any { .. }, message: Some(standalone server listener exit), location: Location { file: "easytier/src/proto/rpc_impl/standalone.rs", line: 113, col: 13 }, can_unwind: true, force_no_backtrace: false }

### 重现步骤 / Reproduction

./easytier-core --network-name xxx --network-secret xxx -p tcp://xxx:xxx -i 192.168.xxx.xxx

**Comment by KKRainbow** [comment]
你用的是啥操作系统？

**Comment by kettly1260** [comment]
用的Ubuntu

**Comment by kettly1260** [comment]
PanicInfo { payload: Any { .. }, message: Some(called `Option::unwrap()` on a `None` value), location: Location { file: "easytier/src/proto/rpc_impl/bidirect.rs", line: 134, col: 44 }, can_unwind: true, force_no_backtrace: false }
Backtrace []
@KKRainbow 还是会不定时停止
