### ISSUE TITLE
404 in  CONTRIBUTING.md  

### ISSUE THREAD

**Issue by hellojason3** [EasyTier/EasyTier#69]
https://github.com/KKRainbow/EasyTier/blob/main/CONTRIBUTING.md  
<img width="1063" alt="Screenshot 2024-05-03 at 19 05 07" src="https://github.com/KKRainbow/EasyTier/assets/119396233/40b4d403-3e04-46b6-8ed6-ade2f3ade721">

**Comment by KKRainbow** [comment]
Sorry, forgot to write this. I'll handle it ASAP.
