### ISSUE TITLE
期待该项目有更好的发展，提一些建议

### ISSUE THREAD

**Issue by OuOumm** [EasyTier/EasyTier#91]
开机自启动安排一下，主要是这个。

gui的话，内存占用可以少一点，或者说，分离出来，可以退出gui之后，服务依旧运行

 还有就是多平台的支持。

其次就是链接会存在不稳定的情况，gui页面显示链接正常，但实际上通过远程桌面连接是连接不上的，提示无法连接服务器

日志也建议完善一下，以便更好的反馈内容。

**Comment by KKRainbow** [comment]
> gui的话，内存占用可以少一点，或者说，分离出来，可以退出gui之后，服务依旧运行

这个可能比较困难，windows 上的内存占用主要来源于 WinTun

> 其次就是链接会存在不稳定的情况，gui页面显示链接正常，但实际上通过远程桌面连接是连接不上的，提示无法连接服务器

这个可能跟 MTU 有关系，我已经做了修复，后续可以测试下

其他的建议都非常合理，我会尽快完成

**Comment by OuOumm** [comment]
> > gui的话，内存占用可以少一点，或者说，分离出来，可以退出gui之后，服务依旧运行
> 
> 这个可能比较困难，windows 上的内存占用主要来源于 WinTun
> 
> > 其次就是链接会存在不稳定的情况，gui页面显示链接正常，但实际上通过远程桌面连接是连接不上的，提示无法连接服务器
> 
> 这个可能跟 MTU 有关系，我已经做了修复，后续可以测试下
> 
> 其他的建议都非常合理，我会尽快完成



> > gui的话，内存占用可以少一点，或者说，分离出来，可以退出gui之后，服务依旧运行
> 
> 这个可能比较困难，windows 上的内存占用主要来源于 WinTun
> 
> > 其次就是链接会存在不稳定的情况，gui页面显示链接正常，但实际上通过远程桌面连接是连接不上的，提示无法连接服务器
> 
> 这个可能跟 MTU 有关系，我已经做了修复，后续可以测试下
> 
> 其他的建议都非常合理，我会尽快完成

幸苦！

**Comment by KKRainbow** [comment]
> > windows 上的内存占用主要来源于 WinTun
> 
> Wintun 内存占用多可能是由于 WintunStartSession 启动时给的 Ring Buffer 太大了,可以考虑设置成 WINTUN_MIN_RING_CAPACITY.
> 
> @KKRainbow

我看看。不知道好不好改，tun 是直接用的 rust-tun 库弄得，不知道有没有暴露接口出来。

感谢提示哈

**Comment by m1m1sha** [comment]
> rust-tun

https://github.com/meh/rust-tun/blob/master/src/platform/windows/device.rs#L52

用的 MAX_RING_CAPACITY ，是写死的

**Comment by lanthora** [comment]
> > rust-tun
> 
> 
> 
> https://github.com/meh/rust-tun/blob/master/src/platform/windows/device.rs#L52
> 
> 
> 
> 用的 MAX_RING_CAPACITY ，是写死的

不怎么了解 Rust，不过看到这行代码附近的几行写死的变量人都麻了

**Comment by rdndsy** [comment]
使用docker compose 安装后一直在restarting，有大神帮忙不
NAME         IMAGE                      COMMAND                  SERVICE      CREATED          STATUS                          PORTS
easytier     easytier/easytier:latest   "easytier-core -i 35…"   easytier     38 minutes ago   Restarting (1) 59 seconds ago
watchtower   containrrr/watchtower      "/watchtower --inter…"   watchtower   38 minutes ago   Up 38 minutes (healthy)         8080/tcp

version: "3.8"
services:
   watchtower: #用于自动更新easytier镜像，若不需要请删除这部分
         command: --interval 3600 --cleanup --label-enable
         container_name: watchtower
         environment:
               - TZ=Asia/Shanghai
               - WATCHTOWER_NO_STARTUP_MESSAGE
         image: containrrr/watchtower
         restart: always
         volumes:
               - /var/run/docker.sock:/var/run/docker.sock
   easytier:
         restart: always
         labels:
               com.centurylinklabs.watchtower.enable: "true"        
         privileged: true
         mem_limit: 0m
         container_name: easytier
         hostname: easytier
         network_mode: host
         volumes:
               - /etc/easytier:/root
         environment:
               - TZ=Asia/Shanghai
         image: easytier/easytier:latest
         command: -i <ip> --network-name <用户> --network-secret <密码> -e tcp://<服务器地址>:11010 -l <监听地址>

<ip> <服务器地址><监听地址> 统一为vps IP地址

**Comment by KKRainbow** [comment]
监听地址改成0.0.0.0

**Comment by rdndsy** [comment]
command: -d 35.212.252.109 --network-name netgo --network-secret netgopass -e tcp://35.212.252.109:11010 -l 0.0.0.0

easytier     easytier/easytier:latest   "easytier-core -d 35…"   easytier     4 minutes ago   Restarting (2) 2 seconds ago
还是无限重启中

**Comment by rdndsy** [comment]
> command: -d --network-name netgo --network-secret netgopass -l tcp://0.0.0.0:11010

感谢，解决
